-- Schema shape after 002: columns, RLS, policies, triggers, indexes, grants, FKs.
-- Generated for TYTAX v2 migration 002; run with: npx -y supabase@2.118.0 test db
begin;
create extension if not exists pgtap with schema extensions;

select plan(142);


select has_column('public', 'profiles', 'updated_at', 'profiles has updated_at');
select has_column('public', 'profiles', 'deleted_at', 'profiles has deleted_at (tombstones)');
select has_column('public', 'profiles', 'created_at', 'profiles has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.profiles'::regclass), 'profiles: RLS enabled');
select policies_are('public', 'profiles', array['profiles_select_own', 'profiles_insert_own', 'profiles_update_own'], 'profiles: exactly the per-command policies');
select has_trigger('public', 'profiles', 'profiles_set_updated_at', 'profiles: server updated_at trigger');
select trigger_is('public', 'profiles', 'profiles_set_updated_at', 'public', 'handle_updated_at', 'profiles: trigger calls handle_updated_at');
select has_index('public', 'profiles', 'profiles_sync_cursor_idx', array['id', 'updated_at'], 'profiles: pull cursor index on (id, updated_at)');
select ok(not has_table_privilege('anon', 'public.profiles', 'select, insert, update, delete, truncate, references, trigger'), 'profiles: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.profiles', 'truncate, references, trigger'), 'profiles: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.profiles', 'select') and has_table_privilege('authenticated', 'public.profiles', 'insert') and has_table_privilege('authenticated', 'public.profiles', 'update'), 'profiles: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.profiles', 'delete'), 'profiles: no client hard delete (tombstones only)');
select has_column('public', 'family_members', 'updated_at', 'family_members has updated_at');
select has_column('public', 'family_members', 'deleted_at', 'family_members has deleted_at (tombstones)');
select has_column('public', 'family_members', 'created_at', 'family_members has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.family_members'::regclass), 'family_members: RLS enabled');
select policies_are('public', 'family_members', array['family_members_select_own', 'family_members_insert_own', 'family_members_update_own'], 'family_members: exactly the per-command policies');
select has_trigger('public', 'family_members', 'family_members_set_updated_at', 'family_members: server updated_at trigger');
select trigger_is('public', 'family_members', 'family_members_set_updated_at', 'public', 'handle_updated_at', 'family_members: trigger calls handle_updated_at');
select has_index('public', 'family_members', 'family_members_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'family_members: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.family_members', 'select, insert, update, delete, truncate, references, trigger'), 'family_members: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.family_members', 'truncate, references, trigger'), 'family_members: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.family_members', 'select') and has_table_privilege('authenticated', 'public.family_members', 'insert') and has_table_privilege('authenticated', 'public.family_members', 'update'), 'family_members: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.family_members', 'delete'), 'family_members: no client hard delete (tombstones only)');
select has_column('public', 'equipment_profiles', 'updated_at', 'equipment_profiles has updated_at');
select has_column('public', 'equipment_profiles', 'deleted_at', 'equipment_profiles has deleted_at (tombstones)');
select has_column('public', 'equipment_profiles', 'created_at', 'equipment_profiles has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.equipment_profiles'::regclass), 'equipment_profiles: RLS enabled');
select policies_are('public', 'equipment_profiles', array['equipment_profiles_select_own', 'equipment_profiles_insert_own', 'equipment_profiles_update_own'], 'equipment_profiles: exactly the per-command policies');
select has_trigger('public', 'equipment_profiles', 'equipment_profiles_set_updated_at', 'equipment_profiles: server updated_at trigger');
select trigger_is('public', 'equipment_profiles', 'equipment_profiles_set_updated_at', 'public', 'handle_updated_at', 'equipment_profiles: trigger calls handle_updated_at');
select has_index('public', 'equipment_profiles', 'equipment_profiles_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'equipment_profiles: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.equipment_profiles', 'select, insert, update, delete, truncate, references, trigger'), 'equipment_profiles: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.equipment_profiles', 'truncate, references, trigger'), 'equipment_profiles: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.equipment_profiles', 'select') and has_table_privilege('authenticated', 'public.equipment_profiles', 'insert') and has_table_privilege('authenticated', 'public.equipment_profiles', 'update'), 'equipment_profiles: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.equipment_profiles', 'delete'), 'equipment_profiles: no client hard delete (tombstones only)');
select has_column('public', 'programs', 'updated_at', 'programs has updated_at');
select has_column('public', 'programs', 'deleted_at', 'programs has deleted_at (tombstones)');
select has_column('public', 'programs', 'created_at', 'programs has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.programs'::regclass), 'programs: RLS enabled');
select policies_are('public', 'programs', array['programs_select_own', 'programs_insert_own', 'programs_update_own'], 'programs: exactly the per-command policies');
select has_trigger('public', 'programs', 'programs_set_updated_at', 'programs: server updated_at trigger');
select trigger_is('public', 'programs', 'programs_set_updated_at', 'public', 'handle_updated_at', 'programs: trigger calls handle_updated_at');
select has_index('public', 'programs', 'programs_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'programs: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.programs', 'select, insert, update, delete, truncate, references, trigger'), 'programs: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.programs', 'truncate, references, trigger'), 'programs: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.programs', 'select') and has_table_privilege('authenticated', 'public.programs', 'insert') and has_table_privilege('authenticated', 'public.programs', 'update'), 'programs: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.programs', 'delete'), 'programs: no client hard delete (tombstones only)');
select has_column('public', 'workout_logs', 'updated_at', 'workout_logs has updated_at');
select has_column('public', 'workout_logs', 'deleted_at', 'workout_logs has deleted_at (tombstones)');
select has_column('public', 'workout_logs', 'created_at', 'workout_logs has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.workout_logs'::regclass), 'workout_logs: RLS enabled');
select policies_are('public', 'workout_logs', array['workout_logs_select_own', 'workout_logs_insert_own', 'workout_logs_update_own'], 'workout_logs: exactly the per-command policies');
select has_trigger('public', 'workout_logs', 'workout_logs_set_updated_at', 'workout_logs: server updated_at trigger');
select trigger_is('public', 'workout_logs', 'workout_logs_set_updated_at', 'public', 'handle_updated_at', 'workout_logs: trigger calls handle_updated_at');
select has_index('public', 'workout_logs', 'workout_logs_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'workout_logs: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.workout_logs', 'select, insert, update, delete, truncate, references, trigger'), 'workout_logs: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.workout_logs', 'truncate, references, trigger'), 'workout_logs: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.workout_logs', 'select') and has_table_privilege('authenticated', 'public.workout_logs', 'insert') and has_table_privilege('authenticated', 'public.workout_logs', 'update'), 'workout_logs: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.workout_logs', 'delete'), 'workout_logs: no client hard delete (tombstones only)');
select has_column('public', 'pr_records', 'updated_at', 'pr_records has updated_at');
select has_column('public', 'pr_records', 'deleted_at', 'pr_records has deleted_at (tombstones)');
select has_column('public', 'pr_records', 'created_at', 'pr_records has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.pr_records'::regclass), 'pr_records: RLS enabled');
select policies_are('public', 'pr_records', array['pr_records_select_own', 'pr_records_insert_own', 'pr_records_update_own'], 'pr_records: exactly the per-command policies');
select has_trigger('public', 'pr_records', 'pr_records_set_updated_at', 'pr_records: server updated_at trigger');
select trigger_is('public', 'pr_records', 'pr_records_set_updated_at', 'public', 'handle_updated_at', 'pr_records: trigger calls handle_updated_at');
select has_index('public', 'pr_records', 'pr_records_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'pr_records: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.pr_records', 'select, insert, update, delete, truncate, references, trigger'), 'pr_records: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.pr_records', 'truncate, references, trigger'), 'pr_records: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.pr_records', 'select') and has_table_privilege('authenticated', 'public.pr_records', 'insert') and has_table_privilege('authenticated', 'public.pr_records', 'update'), 'pr_records: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.pr_records', 'delete'), 'pr_records: no client hard delete (tombstones only)');
select has_column('public', 'bodyweight_entries', 'updated_at', 'bodyweight_entries has updated_at');
select has_column('public', 'bodyweight_entries', 'deleted_at', 'bodyweight_entries has deleted_at (tombstones)');
select has_column('public', 'bodyweight_entries', 'created_at', 'bodyweight_entries has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.bodyweight_entries'::regclass), 'bodyweight_entries: RLS enabled');
select policies_are('public', 'bodyweight_entries', array['bodyweight_entries_select_own', 'bodyweight_entries_insert_own', 'bodyweight_entries_update_own'], 'bodyweight_entries: exactly the per-command policies');
select has_trigger('public', 'bodyweight_entries', 'bodyweight_entries_set_updated_at', 'bodyweight_entries: server updated_at trigger');
select trigger_is('public', 'bodyweight_entries', 'bodyweight_entries_set_updated_at', 'public', 'handle_updated_at', 'bodyweight_entries: trigger calls handle_updated_at');
select has_index('public', 'bodyweight_entries', 'bodyweight_entries_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'bodyweight_entries: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.bodyweight_entries', 'select, insert, update, delete, truncate, references, trigger'), 'bodyweight_entries: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.bodyweight_entries', 'truncate, references, trigger'), 'bodyweight_entries: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.bodyweight_entries', 'select') and has_table_privilege('authenticated', 'public.bodyweight_entries', 'insert') and has_table_privilege('authenticated', 'public.bodyweight_entries', 'update'), 'bodyweight_entries: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.bodyweight_entries', 'delete'), 'bodyweight_entries: no client hard delete (tombstones only)');
select has_column('public', 'exercise_notes', 'updated_at', 'exercise_notes has updated_at');
select has_column('public', 'exercise_notes', 'deleted_at', 'exercise_notes has deleted_at (tombstones)');
select has_column('public', 'exercise_notes', 'created_at', 'exercise_notes has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.exercise_notes'::regclass), 'exercise_notes: RLS enabled');
select policies_are('public', 'exercise_notes', array['exercise_notes_select_own', 'exercise_notes_insert_own', 'exercise_notes_update_own'], 'exercise_notes: exactly the per-command policies');
select has_trigger('public', 'exercise_notes', 'exercise_notes_set_updated_at', 'exercise_notes: server updated_at trigger');
select trigger_is('public', 'exercise_notes', 'exercise_notes_set_updated_at', 'public', 'handle_updated_at', 'exercise_notes: trigger calls handle_updated_at');
select has_index('public', 'exercise_notes', 'exercise_notes_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'exercise_notes: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.exercise_notes', 'select, insert, update, delete, truncate, references, trigger'), 'exercise_notes: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.exercise_notes', 'truncate, references, trigger'), 'exercise_notes: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.exercise_notes', 'select') and has_table_privilege('authenticated', 'public.exercise_notes', 'insert') and has_table_privilege('authenticated', 'public.exercise_notes', 'update'), 'exercise_notes: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.exercise_notes', 'delete'), 'exercise_notes: no client hard delete (tombstones only)');
select has_column('public', 'sync_metadata', 'updated_at', 'sync_metadata has updated_at');
select ok((select relrowsecurity from pg_class where oid = 'public.sync_metadata'::regclass), 'sync_metadata: RLS enabled');
select policies_are('public', 'sync_metadata', array['sync_metadata_select_own', 'sync_metadata_insert_own', 'sync_metadata_update_own'], 'sync_metadata: exactly the per-command policies');
select has_trigger('public', 'sync_metadata', 'sync_metadata_set_updated_at', 'sync_metadata: server updated_at trigger');
select trigger_is('public', 'sync_metadata', 'sync_metadata_set_updated_at', 'public', 'handle_updated_at', 'sync_metadata: trigger calls handle_updated_at');
select has_index('public', 'sync_metadata', 'sync_metadata_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'sync_metadata: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.sync_metadata', 'select, insert, update, delete, truncate, references, trigger'), 'sync_metadata: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.sync_metadata', 'truncate, references, trigger'), 'sync_metadata: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.sync_metadata', 'select') and has_table_privilege('authenticated', 'public.sync_metadata', 'insert') and has_table_privilege('authenticated', 'public.sync_metadata', 'update'), 'sync_metadata: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.sync_metadata', 'delete'), 'sync_metadata: no client hard delete (tombstones only)');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and cmd = 'ALL'$sql$, 'no FOR ALL policies remain');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and roles <> '{authenticated}'::name[]$sql$, 'every policy is TO authenticated only');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and cmd in ('INSERT', 'UPDATE') and with_check is null$sql$, 'every insert/update policy has WITH CHECK');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and cmd in ('SELECT', 'UPDATE', 'DELETE') and qual is null$sql$, 'every select/update/delete policy has USING');
select is_empty($sql$select tgname from pg_trigger where tgrelid::regclass::text like 'public.%' and tgname like 'handle\_%\_updated\_at'$sql$, '001 update-only triggers are gone');
select fk_ok('public', 'equipment_profiles', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'equipment_profiles: composite FK to family_members');
select fk_ok('public', 'programs', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'programs: composite FK to family_members');
select fk_ok('public', 'workout_logs', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'workout_logs: composite FK to family_members');
select fk_ok('public', 'pr_records', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'pr_records: composite FK to family_members');
select fk_ok('public', 'bodyweight_entries', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'bodyweight_entries: composite FK to family_members');
select fk_ok('public', 'exercise_notes', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'exercise_notes: composite FK to family_members');
select fk_ok('public', 'profiles', array['active_family_member_id', 'id'], 'public', 'family_members', array['id', 'profile_id'], 'profiles: composite FK active_family_member_id -> own family_members');
select fk_ok('public', 'profiles', array['active_equipment_profile_id', 'id'], 'public', 'equipment_profiles', array['id', 'profile_id'], 'profiles: composite FK active_equipment_profile_id -> own equipment_profiles');
select is((select count(*) from pg_constraint where contype = 'f' and conname in ('workout_logs_family_member_fk', 'workout_logs_program_fk', 'pr_records_workout_log_fk', 'programs_family_member_fk', 'pr_records_family_member_fk', 'bodyweight_entries_family_member_fk', 'exercise_notes_family_member_fk', 'equipment_profiles_family_member_fk', 'profiles_active_family_member_fk', 'profiles_active_equipment_profile_fk') and condeferrable and not condeferred), 10::bigint, 'all 10 composite FKs are DEFERRABLE INITIALLY IMMEDIATE');
select fk_ok('public', 'workout_logs', array['program_id', 'profile_id'], 'public', 'programs', array['id', 'profile_id'], 'workout_logs: composite FK to programs');
select fk_ok('public', 'pr_records', array['workout_log_id', 'profile_id'], 'public', 'workout_logs', array['id', 'profile_id'], 'pr_records: composite FK to workout_logs');
select is_empty($sql$select conname from pg_constraint where conname in ('workout_logs_family_member_id_fkey', 'workout_logs_program_id_fkey', 'pr_records_workout_log_id_fkey')$sql$, 'plain 001 FKs are gone');
select is_empty($sql$select conname from pg_constraint where conname in ('bodyweight_entries_profile_id_date_key', 'exercise_notes_profile_id_exercise_id_key')$sql$, 'natural-key uniques that break id sync are gone');
select col_type_is('public', 'family_members', 'settings', 'jsonb', 'family_members.settings is jsonb');
select col_not_null('public', 'family_members', 'settings', 'family_members.settings is not null');
select ok((select prosecdef from pg_proc where oid = 'public.handle_new_user()'::regprocedure), 'handle_new_user is SECURITY DEFINER');
select ok((select proconfig @> array['search_path=""'] from pg_proc where oid = 'public.handle_new_user()'::regprocedure), 'handle_new_user pins search_path to empty');
select has_trigger('auth', 'users', 'on_auth_user_created', 'auth.users has the signup trigger');
select ok(not has_function_privilege('authenticated', 'public.handle_new_user()', 'execute') and not has_function_privilege('anon', 'public.handle_new_user()', 'execute'), 'handle_new_user not executable by API roles');
select has_trigger('public', 'profiles', 'profiles_sync_is_anonymous', 'profiles: is_anonymous is mirrored from auth.users by a trigger');
select has_trigger('auth', 'users', 'on_auth_user_is_anonymous_changed', 'auth.users propagates is_anonymous changes');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.handle_profile_is_anonymous()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.handle_profile_is_anonymous()'), 'execute'), false), 'handle_profile_is_anonymous() exists and is not executable by API roles');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.handle_user_is_anonymous_changed()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.handle_user_is_anonymous_changed()'), 'execute'), false), 'handle_user_is_anonymous_changed() exists and is not executable by API roles');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.handle_updated_at()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.handle_updated_at()'), 'execute'), false), 'handle_updated_at() exists and is not executable by API roles');
select ok(coalesce(has_function_privilege('authenticated', to_regprocedure('public.undelete_row(text, uuid)'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.undelete_row(text, uuid)'), 'execute'), false), 'undelete_row exists, authenticated only');
select is_empty($sql$select c.relname from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p') and not c.relrowsecurity$sql$, 'every public table has RLS enabled');
select is_empty($sql$select c.relname from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p', 'v', 'm', 'f') and has_table_privilege('anon', c.oid, 'select, insert, update, delete, truncate, references, trigger')$sql$, 'anon holds no privilege on any public table or view');
create table public.zz_future_probe (id int);
create function public.zz_future_fn() returns int language sql as 'select 1';
create sequence public.zz_future_seq;

select ok(not has_table_privilege('anon', 'public.zz_future_probe', 'select, insert, update, delete, truncate, references, trigger'), 'default privileges: anon gets nothing on a future public table');
select ok(not has_table_privilege('authenticated', 'public.zz_future_probe', 'truncate, references, trigger'), 'default privileges: authenticated gets no TRUNCATE/REFERENCES/TRIGGER on a future public table');
select ok(not has_function_privilege('anon', 'public.zz_future_fn()', 'execute') and not has_function_privilege('authenticated', 'public.zz_future_fn()', 'execute'), 'default privileges: a future public function is not executable by anon/authenticated');
select ok(not has_sequence_privilege('anon', 'public.zz_future_seq', 'usage, select, update'), 'default privileges: anon gets nothing on a future public sequence');
drop table public.zz_future_probe;
drop function public.zz_future_fn();
drop sequence public.zz_future_seq;

select * from finish();
rollback;
