-- Schema shape after 002-004: columns, RLS, policies, triggers, indexes, grants, FKs.
-- Generated for TYTAX v2 migrations 002-004; run with: npx -y supabase@2.118.0 test db
begin;
create extension if not exists pgtap with schema extensions;

select plan(263);


select has_column('public', 'profiles', 'updated_at', 'profiles has updated_at');
select has_column('public', 'profiles', 'deleted_at', 'profiles has deleted_at (tombstones)');
select has_column('public', 'profiles', 'created_at', 'profiles has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.profiles'::regclass), 'profiles: RLS enabled');
select policies_are('public', 'profiles', array['profiles_select_own', 'profiles_insert_own', 'profiles_update_own'], 'profiles: exactly the per-command policies');
select has_trigger('public', 'profiles', 'profiles_set_updated_at', 'profiles: server updated_at trigger');
select trigger_is('public', 'profiles', 'profiles_set_updated_at', 'public', 'handle_updated_at', 'profiles: trigger calls handle_updated_at');
select has_index('public', 'profiles', 'profiles_sync_cursor_idx', array['id', 'updated_at'], 'profiles: pull cursor index on (id, updated_at)');
select ok(not has_table_privilege('anon', 'public.profiles', 'select, insert, update, delete, truncate, references, trigger'), 'profiles: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.profiles', 'truncate, references, trigger'), 'profiles: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.profiles', 'select') and has_table_privilege('authenticated', 'public.profiles', 'insert') and has_table_privilege('authenticated', 'public.profiles', 'update'), 'profiles: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.profiles', 'delete'), 'profiles: no client hard delete (tombstones only)');
select has_column('public', 'family_members', 'updated_at', 'family_members has updated_at');
select has_column('public', 'family_members', 'deleted_at', 'family_members has deleted_at (tombstones)');
select has_column('public', 'family_members', 'created_at', 'family_members has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.family_members'::regclass), 'family_members: RLS enabled');
select policies_are('public', 'family_members', array['family_members_select_own', 'family_members_insert_own', 'family_members_update_own'], 'family_members: exactly the per-command policies');
select has_trigger('public', 'family_members', 'family_members_set_updated_at', 'family_members: server updated_at trigger');
select trigger_is('public', 'family_members', 'family_members_set_updated_at', 'public', 'handle_updated_at', 'family_members: trigger calls handle_updated_at');
select has_index('public', 'family_members', 'family_members_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'family_members: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.family_members', 'select, insert, update, delete, truncate, references, trigger'), 'family_members: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.family_members', 'truncate, references, trigger'), 'family_members: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.family_members', 'select') and has_table_privilege('authenticated', 'public.family_members', 'insert') and has_table_privilege('authenticated', 'public.family_members', 'update'), 'family_members: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.family_members', 'delete'), 'family_members: no client hard delete (tombstones only)');
select has_column('public', 'equipment_profiles', 'updated_at', 'equipment_profiles has updated_at');
select has_column('public', 'equipment_profiles', 'deleted_at', 'equipment_profiles has deleted_at (tombstones)');
select has_column('public', 'equipment_profiles', 'created_at', 'equipment_profiles has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.equipment_profiles'::regclass), 'equipment_profiles: RLS enabled');
select policies_are('public', 'equipment_profiles', array['equipment_profiles_select_own', 'equipment_profiles_insert_own', 'equipment_profiles_update_own'], 'equipment_profiles: exactly the per-command policies');
select has_trigger('public', 'equipment_profiles', 'equipment_profiles_set_updated_at', 'equipment_profiles: server updated_at trigger');
select trigger_is('public', 'equipment_profiles', 'equipment_profiles_set_updated_at', 'public', 'handle_updated_at', 'equipment_profiles: trigger calls handle_updated_at');
select has_index('public', 'equipment_profiles', 'equipment_profiles_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'equipment_profiles: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.equipment_profiles', 'select, insert, update, delete, truncate, references, trigger'), 'equipment_profiles: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.equipment_profiles', 'truncate, references, trigger'), 'equipment_profiles: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.equipment_profiles', 'select') and has_table_privilege('authenticated', 'public.equipment_profiles', 'insert') and has_table_privilege('authenticated', 'public.equipment_profiles', 'update'), 'equipment_profiles: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.equipment_profiles', 'delete'), 'equipment_profiles: no client hard delete (tombstones only)');
select has_column('public', 'programs', 'updated_at', 'programs has updated_at');
select has_column('public', 'programs', 'deleted_at', 'programs has deleted_at (tombstones)');
select has_column('public', 'programs', 'created_at', 'programs has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.programs'::regclass), 'programs: RLS enabled');
select policies_are('public', 'programs', array['programs_select_own', 'programs_insert_own', 'programs_update_own'], 'programs: exactly the per-command policies');
select has_trigger('public', 'programs', 'programs_set_updated_at', 'programs: server updated_at trigger');
select trigger_is('public', 'programs', 'programs_set_updated_at', 'public', 'handle_updated_at', 'programs: trigger calls handle_updated_at');
select has_index('public', 'programs', 'programs_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'programs: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.programs', 'select, insert, update, delete, truncate, references, trigger'), 'programs: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.programs', 'truncate, references, trigger'), 'programs: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.programs', 'select') and has_table_privilege('authenticated', 'public.programs', 'insert') and has_table_privilege('authenticated', 'public.programs', 'update'), 'programs: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.programs', 'delete'), 'programs: no client hard delete (tombstones only)');
select has_column('public', 'workout_logs', 'updated_at', 'workout_logs has updated_at');
select has_column('public', 'workout_logs', 'deleted_at', 'workout_logs has deleted_at (tombstones)');
select has_column('public', 'workout_logs', 'created_at', 'workout_logs has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.workout_logs'::regclass), 'workout_logs: RLS enabled');
select policies_are('public', 'workout_logs', array['workout_logs_select_own', 'workout_logs_insert_own', 'workout_logs_update_own'], 'workout_logs: exactly the per-command policies');
select has_trigger('public', 'workout_logs', 'workout_logs_set_updated_at', 'workout_logs: server updated_at trigger');
select trigger_is('public', 'workout_logs', 'workout_logs_set_updated_at', 'public', 'handle_updated_at', 'workout_logs: trigger calls handle_updated_at');
select has_index('public', 'workout_logs', 'workout_logs_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'workout_logs: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.workout_logs', 'select, insert, update, delete, truncate, references, trigger'), 'workout_logs: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.workout_logs', 'truncate, references, trigger'), 'workout_logs: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.workout_logs', 'select') and has_table_privilege('authenticated', 'public.workout_logs', 'insert') and has_table_privilege('authenticated', 'public.workout_logs', 'update'), 'workout_logs: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.workout_logs', 'delete'), 'workout_logs: no client hard delete (tombstones only)');
select has_column('public', 'pr_records', 'updated_at', 'pr_records has updated_at');
select has_column('public', 'pr_records', 'deleted_at', 'pr_records has deleted_at (tombstones)');
select has_column('public', 'pr_records', 'created_at', 'pr_records has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.pr_records'::regclass), 'pr_records: RLS enabled');
select policies_are('public', 'pr_records', array['pr_records_select_own', 'pr_records_insert_own', 'pr_records_update_own'], 'pr_records: exactly the per-command policies');
select has_trigger('public', 'pr_records', 'pr_records_set_updated_at', 'pr_records: server updated_at trigger');
select trigger_is('public', 'pr_records', 'pr_records_set_updated_at', 'public', 'handle_updated_at', 'pr_records: trigger calls handle_updated_at');
select has_index('public', 'pr_records', 'pr_records_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'pr_records: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.pr_records', 'select, insert, update, delete, truncate, references, trigger'), 'pr_records: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.pr_records', 'truncate, references, trigger'), 'pr_records: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.pr_records', 'select') and has_table_privilege('authenticated', 'public.pr_records', 'insert') and has_table_privilege('authenticated', 'public.pr_records', 'update'), 'pr_records: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.pr_records', 'delete'), 'pr_records: no client hard delete (tombstones only)');
select has_column('public', 'bodyweight_entries', 'updated_at', 'bodyweight_entries has updated_at');
select has_column('public', 'bodyweight_entries', 'deleted_at', 'bodyweight_entries has deleted_at (tombstones)');
select has_column('public', 'bodyweight_entries', 'created_at', 'bodyweight_entries has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.bodyweight_entries'::regclass), 'bodyweight_entries: RLS enabled');
select policies_are('public', 'bodyweight_entries', array['bodyweight_entries_select_own', 'bodyweight_entries_insert_own', 'bodyweight_entries_update_own'], 'bodyweight_entries: exactly the per-command policies');
select has_trigger('public', 'bodyweight_entries', 'bodyweight_entries_set_updated_at', 'bodyweight_entries: server updated_at trigger');
select trigger_is('public', 'bodyweight_entries', 'bodyweight_entries_set_updated_at', 'public', 'handle_updated_at', 'bodyweight_entries: trigger calls handle_updated_at');
select has_index('public', 'bodyweight_entries', 'bodyweight_entries_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'bodyweight_entries: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.bodyweight_entries', 'select, insert, update, delete, truncate, references, trigger'), 'bodyweight_entries: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.bodyweight_entries', 'truncate, references, trigger'), 'bodyweight_entries: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.bodyweight_entries', 'select') and has_table_privilege('authenticated', 'public.bodyweight_entries', 'insert') and has_table_privilege('authenticated', 'public.bodyweight_entries', 'update'), 'bodyweight_entries: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.bodyweight_entries', 'delete'), 'bodyweight_entries: no client hard delete (tombstones only)');
select has_column('public', 'exercise_notes', 'updated_at', 'exercise_notes has updated_at');
select has_column('public', 'exercise_notes', 'deleted_at', 'exercise_notes has deleted_at (tombstones)');
select has_column('public', 'exercise_notes', 'created_at', 'exercise_notes has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.exercise_notes'::regclass), 'exercise_notes: RLS enabled');
select policies_are('public', 'exercise_notes', array['exercise_notes_select_own', 'exercise_notes_insert_own', 'exercise_notes_update_own'], 'exercise_notes: exactly the per-command policies');
select has_trigger('public', 'exercise_notes', 'exercise_notes_set_updated_at', 'exercise_notes: server updated_at trigger');
select trigger_is('public', 'exercise_notes', 'exercise_notes_set_updated_at', 'public', 'handle_updated_at', 'exercise_notes: trigger calls handle_updated_at');
select has_index('public', 'exercise_notes', 'exercise_notes_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'exercise_notes: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.exercise_notes', 'select, insert, update, delete, truncate, references, trigger'), 'exercise_notes: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.exercise_notes', 'truncate, references, trigger'), 'exercise_notes: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.exercise_notes', 'select') and has_table_privilege('authenticated', 'public.exercise_notes', 'insert') and has_table_privilege('authenticated', 'public.exercise_notes', 'update'), 'exercise_notes: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.exercise_notes', 'delete'), 'exercise_notes: no client hard delete (tombstones only)');
select has_column('public', 'sync_metadata', 'updated_at', 'sync_metadata has updated_at');
select ok((select relrowsecurity from pg_class where oid = 'public.sync_metadata'::regclass), 'sync_metadata: RLS enabled');
select policies_are('public', 'sync_metadata', array['sync_metadata_select_own', 'sync_metadata_insert_own', 'sync_metadata_update_own'], 'sync_metadata: exactly the per-command policies');
select has_trigger('public', 'sync_metadata', 'sync_metadata_set_updated_at', 'sync_metadata: server updated_at trigger');
select trigger_is('public', 'sync_metadata', 'sync_metadata_set_updated_at', 'public', 'handle_updated_at', 'sync_metadata: trigger calls handle_updated_at');
select has_index('public', 'sync_metadata', 'sync_metadata_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'sync_metadata: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.sync_metadata', 'select, insert, update, delete, truncate, references, trigger'), 'sync_metadata: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.sync_metadata', 'truncate, references, trigger'), 'sync_metadata: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.sync_metadata', 'select') and has_table_privilege('authenticated', 'public.sync_metadata', 'insert') and has_table_privilege('authenticated', 'public.sync_metadata', 'update'), 'sync_metadata: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.sync_metadata', 'delete'), 'sync_metadata: no client hard delete (tombstones only)');
select has_column('public', 'arsenal', 'updated_at', 'arsenal has updated_at');
select has_column('public', 'arsenal', 'deleted_at', 'arsenal has deleted_at (tombstones)');
select has_column('public', 'arsenal', 'created_at', 'arsenal has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.arsenal'::regclass), 'arsenal: RLS enabled');
select policies_are('public', 'arsenal', array['arsenal_select_own', 'arsenal_insert_own', 'arsenal_update_own'], 'arsenal: exactly the per-command policies');
select has_trigger('public', 'arsenal', 'arsenal_set_updated_at', 'arsenal: server updated_at trigger');
select trigger_is('public', 'arsenal', 'arsenal_set_updated_at', 'public', 'handle_updated_at', 'arsenal: trigger calls handle_updated_at');
select has_index('public', 'arsenal', 'arsenal_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'arsenal: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.arsenal', 'select, insert, update, delete, truncate, references, trigger'), 'arsenal: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.arsenal', 'truncate, references, trigger'), 'arsenal: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.arsenal', 'select') and has_table_privilege('authenticated', 'public.arsenal', 'insert') and has_table_privilege('authenticated', 'public.arsenal', 'update'), 'arsenal: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.arsenal', 'delete'), 'arsenal: no client hard delete (tombstones only)');
select has_column('public', 'equipment', 'updated_at', 'equipment has updated_at');
select has_column('public', 'equipment', 'deleted_at', 'equipment has deleted_at (tombstones)');
select has_column('public', 'equipment', 'created_at', 'equipment has created_at');
select ok((select relrowsecurity from pg_class where oid = 'public.equipment'::regclass), 'equipment: RLS enabled');
select policies_are('public', 'equipment', array['equipment_select_own', 'equipment_insert_own', 'equipment_update_own'], 'equipment: exactly the per-command policies');
select has_trigger('public', 'equipment', 'equipment_set_updated_at', 'equipment: server updated_at trigger');
select trigger_is('public', 'equipment', 'equipment_set_updated_at', 'public', 'handle_updated_at', 'equipment: trigger calls handle_updated_at');
select has_index('public', 'equipment', 'equipment_sync_cursor_idx', array['profile_id', 'updated_at', 'id'], 'equipment: pull cursor index on (profile_id, updated_at, id)');
select ok(not has_table_privilege('anon', 'public.equipment', 'select, insert, update, delete, truncate, references, trigger'), 'equipment: anon has no privileges');
select ok(not has_table_privilege('authenticated', 'public.equipment', 'truncate, references, trigger'), 'equipment: authenticated cannot truncate (RLS bypass)');
select ok(has_table_privilege('authenticated', 'public.equipment', 'select') and has_table_privilege('authenticated', 'public.equipment', 'insert') and has_table_privilege('authenticated', 'public.equipment', 'update'), 'equipment: authenticated can select/insert/update');
select ok(not has_table_privilege('authenticated', 'public.equipment', 'delete'), 'equipment: no client hard delete (tombstones only)');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and cmd = 'ALL'$sql$, 'no FOR ALL policies remain');
select is((select count(*) from pg_policies where schemaname = 'public'), 33::bigint, '33 per-command policies (11 tables x select/insert/update)');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and roles <> '{authenticated}'::name[]$sql$, 'every policy is TO authenticated only');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and cmd in ('INSERT', 'UPDATE') and with_check is null$sql$, 'every insert/update policy has WITH CHECK');
select is_empty($sql$select 1 from pg_policies where schemaname = 'public' and cmd in ('SELECT', 'UPDATE', 'DELETE') and qual is null$sql$, 'every select/update/delete policy has USING');
select is_empty($sql$select tablename || '.' || policyname from pg_policies where schemaname = 'public' and cmd in ('INSERT', 'UPDATE') and with_check is distinct from '(( SELECT auth.uid() AS uid) = ' || case when tablename = 'profiles' then 'id' else 'profile_id' end || ')'$sql$, 'every insert/update WITH CHECK is exactly auth.uid() = owner column');
select is_empty($sql$select tablename || '.' || policyname from pg_policies where schemaname = 'public' and cmd in ('SELECT', 'UPDATE') and qual is distinct from '(( SELECT auth.uid() AS uid) = ' || case when tablename = 'profiles' then 'id' else 'profile_id' end || ')'$sql$, 'every select/update USING is exactly auth.uid() = owner column');
select is_empty($sql$select tablename || '.' || policyname from pg_policies where schemaname = 'public' and cmd = 'INSERT' and qual is not null$sql$, 'insert policies carry no USING (only WITH CHECK applies)');
select is_empty($sql$select tgname from pg_trigger where tgrelid::regclass::text like 'public.%' and tgname like 'handle\_%\_updated\_at'$sql$, '001 update-only triggers are gone');
select fk_ok('public', 'equipment_profiles', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'equipment_profiles: composite FK to family_members');
select fk_ok('public', 'programs', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'programs: composite FK to family_members');
select fk_ok('public', 'workout_logs', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'workout_logs: composite FK to family_members');
select fk_ok('public', 'pr_records', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'pr_records: composite FK to family_members');
select fk_ok('public', 'bodyweight_entries', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'bodyweight_entries: composite FK to family_members');
select fk_ok('public', 'exercise_notes', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'exercise_notes: composite FK to family_members');
select fk_ok('public', 'arsenal', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'arsenal: composite FK to family_members');
select fk_ok('public', 'equipment', array['family_member_id', 'profile_id'], 'public', 'family_members', array['id', 'profile_id'], 'equipment: composite FK to family_members');
select fk_ok('public', 'profiles', array['active_family_member_id', 'id'], 'public', 'family_members', array['id', 'profile_id'], 'profiles: composite FK active_family_member_id -> own family_members');
select fk_ok('public', 'profiles', array['active_equipment_profile_id', 'id'], 'public', 'equipment_profiles', array['id', 'profile_id'], 'profiles: composite FK active_equipment_profile_id -> own equipment_profiles');
select is((select count(*) from pg_constraint where contype = 'f' and conname in ('workout_logs_family_member_fk', 'workout_logs_program_fk', 'pr_records_workout_log_fk', 'programs_family_member_fk', 'pr_records_family_member_fk', 'bodyweight_entries_family_member_fk', 'exercise_notes_family_member_fk', 'equipment_profiles_family_member_fk', 'profiles_active_family_member_fk', 'profiles_active_equipment_profile_fk', 'arsenal_family_member_fk', 'equipment_family_member_fk', 'family_members_active_program_fk') and condeferrable and not condeferred), 13::bigint, 'all 13 composite FKs are DEFERRABLE INITIALLY IMMEDIATE');
select fk_ok('public', 'workout_logs', array['program_id', 'profile_id'], 'public', 'programs', array['id', 'profile_id'], 'workout_logs: composite FK to programs');
select fk_ok('public', 'pr_records', array['workout_log_id', 'profile_id'], 'public', 'workout_logs', array['id', 'profile_id'], 'pr_records: composite FK to workout_logs');
select is_empty($sql$select conname from pg_constraint where conname in ('workout_logs_family_member_id_fkey', 'workout_logs_program_id_fkey', 'pr_records_workout_log_id_fkey')$sql$, 'plain 001 FKs are gone');
select is_empty($sql$select conname from pg_constraint where conname in ('bodyweight_entries_profile_id_date_key', 'exercise_notes_profile_id_exercise_id_key')$sql$, 'natural-key uniques that break id sync are gone');
select col_type_is('public', 'family_members', 'settings', 'jsonb', 'family_members.settings is jsonb');
select col_type_is('public', 'family_members', 'extra', 'jsonb', 'family_members.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'family_members', 'extra', 'family_members.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'family_members' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'family_members.extra defaults to an empty object');
select col_type_is('public', 'workout_logs', 'extra', 'jsonb', 'workout_logs.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'workout_logs', 'extra', 'workout_logs.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'workout_logs' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'workout_logs.extra defaults to an empty object');
select col_type_is('public', 'programs', 'extra', 'jsonb', 'programs.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'programs', 'extra', 'programs.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'programs' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'programs.extra defaults to an empty object');
select col_type_is('public', 'pr_records', 'extra', 'jsonb', 'pr_records.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'pr_records', 'extra', 'pr_records.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'pr_records' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'pr_records.extra defaults to an empty object');
select col_type_is('public', 'bodyweight_entries', 'extra', 'jsonb', 'bodyweight_entries.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'bodyweight_entries', 'extra', 'bodyweight_entries.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'bodyweight_entries' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'bodyweight_entries.extra defaults to an empty object');
select col_type_is('public', 'exercise_notes', 'extra', 'jsonb', 'exercise_notes.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'exercise_notes', 'extra', 'exercise_notes.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'exercise_notes' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'exercise_notes.extra defaults to an empty object');
select col_type_is('public', 'arsenal', 'extra', 'jsonb', 'arsenal.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'arsenal', 'extra', 'arsenal.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'arsenal' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'arsenal.extra defaults to an empty object');
select col_type_is('public', 'equipment', 'extra', 'jsonb', 'equipment.extra is jsonb (unknown fields round-trip)');
select col_not_null('public', 'equipment', 'extra', 'equipment.extra is not null');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'equipment' and column_name = 'extra'), $d$'{}'::jsonb$d$, 'equipment.extra defaults to an empty object');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'family_members' and column_name = 'profile_id'), 'auth.uid()', 'family_members.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'equipment_profiles' and column_name = 'profile_id'), 'auth.uid()', 'equipment_profiles.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'programs' and column_name = 'profile_id'), 'auth.uid()', 'programs.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'workout_logs' and column_name = 'profile_id'), 'auth.uid()', 'workout_logs.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'pr_records' and column_name = 'profile_id'), 'auth.uid()', 'pr_records.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'bodyweight_entries' and column_name = 'profile_id'), 'auth.uid()', 'bodyweight_entries.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'exercise_notes' and column_name = 'profile_id'), 'auth.uid()', 'exercise_notes.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'sync_metadata' and column_name = 'profile_id'), 'auth.uid()', 'sync_metadata.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'arsenal' and column_name = 'profile_id'), 'auth.uid()', 'arsenal.profile_id defaults to auth.uid()');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'equipment' and column_name = 'profile_id'), 'auth.uid()', 'equipment.profile_id defaults to auth.uid()');
select col_type_is('public', 'family_members', 'avatar_color', 'text', 'family_members.avatar_color is text (003)');
select col_type_is('public', 'family_members', 'active_program_id', 'uuid', 'family_members.active_program_id is uuid (003)');
select col_type_is('public', 'workout_logs', 'program_session_id', 'text', 'workout_logs.program_session_id is text (003)');
select col_type_is('public', 'workout_logs', 'is_deload', 'boolean', 'workout_logs.is_deload is boolean (003)');
select col_type_is('public', 'programs', 'preset_id', 'text', 'programs.preset_id is text (003)');
select col_type_is('public', 'pr_records', 'kg', 'real', 'pr_records.kg is real (003)');
select col_type_is('public', 'pr_records', 'set_id', 'text', 'pr_records.set_id is text (003)');
select col_type_is('public', 'pr_records', 'is_baseline', 'boolean', 'pr_records.is_baseline is boolean (003)');
select col_type_is('public', 'arsenal', 'exercise_id', 'text', 'arsenal.exercise_id is text (003)');
select col_type_is('public', 'arsenal', 'added_at', 'timestamp with time zone', 'arsenal.added_at is timestamp with time zone (003)');
select col_type_is('public', 'equipment', 'station_ids', 'text[]', 'equipment.station_ids is text[] (003)');
select col_type_is('public', 'equipment', 'attachment_ids', 'text[]', 'equipment.attachment_ids is text[] (003)');
select col_type_is('public', 'equipment', 'kettlebells_kg', 'real[]', 'equipment.kettlebells_kg is real[] (003)');
select col_type_is('public', 'equipment', 'bodyweight_gear', 'text[]', 'equipment.bodyweight_gear is text[] (003)');
select col_not_null('public', 'arsenal', 'family_member_id', 'arsenal.family_member_id is NOT NULL');
select col_not_null('public', 'equipment', 'family_member_id', 'equipment.family_member_id is NOT NULL');
select is((select column_default from information_schema.columns where table_schema = 'public' and table_name = 'pr_records' and column_name = 'is_baseline'), 'false', 'pr_records.is_baseline defaults to false');
select fk_ok('public', 'family_members', array['active_program_id', 'profile_id'], 'public', 'programs', array['id', 'profile_id'], 'family_members: composite FK active_program_id -> own programs');
select col_not_null('public', 'family_members', 'settings', 'family_members.settings is not null');
select ok((select prosecdef from pg_proc where oid = 'public.handle_new_user()'::regprocedure), 'handle_new_user is SECURITY DEFINER');
select ok((select proconfig @> array['search_path=""'] from pg_proc where oid = 'public.handle_new_user()'::regprocedure), 'handle_new_user pins search_path to empty');
select has_trigger('auth', 'users', 'on_auth_user_created', 'auth.users has the signup trigger');
select ok(not has_function_privilege('authenticated', 'public.handle_new_user()', 'execute') and not has_function_privilege('anon', 'public.handle_new_user()', 'execute'), 'handle_new_user not executable by API roles');
select has_trigger('public', 'profiles', 'profiles_sync_is_anonymous', 'profiles: is_anonymous is mirrored from auth.users by a trigger');
select has_trigger('auth', 'users', 'on_auth_user_is_anonymous_changed', 'auth.users propagates is_anonymous changes');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.handle_profile_is_anonymous()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.handle_profile_is_anonymous()'), 'execute'), false), 'handle_profile_is_anonymous() exists and is not executable by API roles');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.handle_user_is_anonymous_changed()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.handle_user_is_anonymous_changed()'), 'execute'), false), 'handle_user_is_anonymous_changed() exists and is not executable by API roles');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.handle_updated_at()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.handle_updated_at()'), 'execute'), false), 'handle_updated_at() exists and is not executable by API roles');
select ok(coalesce(has_function_privilege('authenticated', to_regprocedure('public.undelete_row(text, uuid)'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.undelete_row(text, uuid)'), 'execute'), false), 'undelete_row exists, authenticated only');
select has_table('public', 'sync_usage', '004: sync_usage exists');
select ok(not has_table_privilege('authenticated', 'public.sync_usage', 'select, insert, update, delete, truncate, references, trigger') and not has_table_privilege('anon', 'public.sync_usage', 'select, insert, update, delete, truncate, references, trigger'), 'sync_usage: no privileges for API roles');
select policies_are('public', 'sync_usage', array[]::name[], 'sync_usage: no policies (server-internal)');
select has_table('public', 'migration_repair_archive', '002: migration_repair_archive exists');
select ok(not has_table_privilege('authenticated', 'public.migration_repair_archive', 'select, insert, update, delete, truncate, references, trigger') and not has_table_privilege('anon', 'public.migration_repair_archive', 'select, insert, update, delete, truncate, references, trigger'), 'migration_repair_archive: no privileges for API roles');
select policies_are('public', 'migration_repair_archive', array[]::name[], 'migration_repair_archive: no policies (server-internal)');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.enforce_sync_quota()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.enforce_sync_quota()'), 'execute'), false), 'enforce_sync_quota() exists and is not executable by API roles');
select ok(coalesce(not has_function_privilege('authenticated', to_regprocedure('public.sync_quota()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.sync_quota()'), 'execute'), false), 'sync_quota() exists and is not executable by API roles');
select ok((select prosecdef from pg_proc where oid = 'public.enforce_sync_quota()'::regprocedure), 'enforce_sync_quota is SECURITY DEFINER (writes sync_usage)');
select trigger_is('public', 'family_members', 'family_members_quota_ins', 'public', 'enforce_sync_quota', 'family_members: quota trigger ins');
select trigger_is('public', 'family_members', 'family_members_quota_upd', 'public', 'enforce_sync_quota', 'family_members: quota trigger upd');
select trigger_is('public', 'family_members', 'family_members_quota_del', 'public', 'enforce_sync_quota', 'family_members: quota trigger del');
select trigger_is('public', 'equipment_profiles', 'equipment_profiles_quota_ins', 'public', 'enforce_sync_quota', 'equipment_profiles: quota trigger ins');
select trigger_is('public', 'equipment_profiles', 'equipment_profiles_quota_upd', 'public', 'enforce_sync_quota', 'equipment_profiles: quota trigger upd');
select trigger_is('public', 'equipment_profiles', 'equipment_profiles_quota_del', 'public', 'enforce_sync_quota', 'equipment_profiles: quota trigger del');
select trigger_is('public', 'programs', 'programs_quota_ins', 'public', 'enforce_sync_quota', 'programs: quota trigger ins');
select trigger_is('public', 'programs', 'programs_quota_upd', 'public', 'enforce_sync_quota', 'programs: quota trigger upd');
select trigger_is('public', 'programs', 'programs_quota_del', 'public', 'enforce_sync_quota', 'programs: quota trigger del');
select trigger_is('public', 'workout_logs', 'workout_logs_quota_ins', 'public', 'enforce_sync_quota', 'workout_logs: quota trigger ins');
select trigger_is('public', 'workout_logs', 'workout_logs_quota_upd', 'public', 'enforce_sync_quota', 'workout_logs: quota trigger upd');
select trigger_is('public', 'workout_logs', 'workout_logs_quota_del', 'public', 'enforce_sync_quota', 'workout_logs: quota trigger del');
select trigger_is('public', 'pr_records', 'pr_records_quota_ins', 'public', 'enforce_sync_quota', 'pr_records: quota trigger ins');
select trigger_is('public', 'pr_records', 'pr_records_quota_upd', 'public', 'enforce_sync_quota', 'pr_records: quota trigger upd');
select trigger_is('public', 'pr_records', 'pr_records_quota_del', 'public', 'enforce_sync_quota', 'pr_records: quota trigger del');
select trigger_is('public', 'bodyweight_entries', 'bodyweight_entries_quota_ins', 'public', 'enforce_sync_quota', 'bodyweight_entries: quota trigger ins');
select trigger_is('public', 'bodyweight_entries', 'bodyweight_entries_quota_upd', 'public', 'enforce_sync_quota', 'bodyweight_entries: quota trigger upd');
select trigger_is('public', 'bodyweight_entries', 'bodyweight_entries_quota_del', 'public', 'enforce_sync_quota', 'bodyweight_entries: quota trigger del');
select trigger_is('public', 'exercise_notes', 'exercise_notes_quota_ins', 'public', 'enforce_sync_quota', 'exercise_notes: quota trigger ins');
select trigger_is('public', 'exercise_notes', 'exercise_notes_quota_upd', 'public', 'enforce_sync_quota', 'exercise_notes: quota trigger upd');
select trigger_is('public', 'exercise_notes', 'exercise_notes_quota_del', 'public', 'enforce_sync_quota', 'exercise_notes: quota trigger del');
select trigger_is('public', 'sync_metadata', 'sync_metadata_quota_ins', 'public', 'enforce_sync_quota', 'sync_metadata: quota trigger ins');
select trigger_is('public', 'sync_metadata', 'sync_metadata_quota_upd', 'public', 'enforce_sync_quota', 'sync_metadata: quota trigger upd');
select trigger_is('public', 'sync_metadata', 'sync_metadata_quota_del', 'public', 'enforce_sync_quota', 'sync_metadata: quota trigger del');
select trigger_is('public', 'arsenal', 'arsenal_quota_ins', 'public', 'enforce_sync_quota', 'arsenal: quota trigger ins');
select trigger_is('public', 'arsenal', 'arsenal_quota_upd', 'public', 'enforce_sync_quota', 'arsenal: quota trigger upd');
select trigger_is('public', 'arsenal', 'arsenal_quota_del', 'public', 'enforce_sync_quota', 'arsenal: quota trigger del');
select trigger_is('public', 'equipment', 'equipment_quota_ins', 'public', 'enforce_sync_quota', 'equipment: quota trigger ins');
select trigger_is('public', 'equipment', 'equipment_quota_upd', 'public', 'enforce_sync_quota', 'equipment: quota trigger upd');
select trigger_is('public', 'equipment', 'equipment_quota_del', 'public', 'enforce_sync_quota', 'equipment: quota trigger del');
select is_empty($sql$select c.relname from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p') and not c.relrowsecurity$sql$, 'every public table has RLS enabled');
select is_empty($sql$select c.relname from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p', 'v', 'm', 'f') and has_table_privilege('anon', c.oid, 'select, insert, update, delete, truncate, references, trigger')$sql$, 'anon holds no privilege on any public table or view');
create table public.zz_future_probe (id int);
create function public.zz_future_fn() returns int language sql as 'select 1';
create sequence public.zz_future_seq;

select ok(not has_table_privilege('anon', 'public.zz_future_probe', 'select, insert, update, delete, truncate, references, trigger'), 'default privileges: anon gets nothing on a future public table');
select ok(not has_table_privilege('authenticated', 'public.zz_future_probe', 'truncate, references, trigger'), 'default privileges: authenticated gets no TRUNCATE/REFERENCES/TRIGGER on a future public table');
select ok(not has_function_privilege('anon', 'public.zz_future_fn()', 'execute') and not has_function_privilege('authenticated', 'public.zz_future_fn()', 'execute'), 'default privileges: a future public function is not executable by anon/authenticated');
select ok(not has_sequence_privilege('anon', 'public.zz_future_seq', 'usage, select, update'), 'default privileges: anon gets nothing on a future public sequence');
drop table public.zz_future_probe;
drop function public.zz_future_fn();
drop sequence public.zz_future_seq;

select * from finish();
rollback;
