import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import i18next from "eslint-plugin-i18next";

// ─── Test-suite guards (PLAN §10.1 W0.5, §10.2) ─────────────────────────────
// ESLint flat config replaces a rule's options wholesale when a later block
// sets the same rule, so the e2e block below repeats SKIP_SELECTORS.

const RUNNERS = "/^(test|it|describe|suite|bench)$/";
const SKIPPERS = "/^(skip|only|fixme|todo|skipIf|runIf)$/";
const SKIP_MESSAGE =
  "No skipped, focused or todo tests (.skip/.only/.fixme/.todo/.skipIf/.runIf): fix the test or delete it.";

/** test.skip, it.only, describe.todo, test.describe.skip, test.describe.parallel.only, it.concurrent.skip, … */
const SKIP_SELECTORS = [
  `MemberExpression[object.name=${RUNNERS}][property.name=${SKIPPERS}]`,
  `MemberExpression[object.object.name=${RUNNERS}][property.name=${SKIPPERS}]`,
  `MemberExpression[object.object.object.name=${RUNNERS}][property.name=${SKIPPERS}]`,
  // Runtime skips from inside a test: testInfo.skip(), test.info().fixme(), vitest ctx.skip().
  "CallExpression[callee.object.name=/^(testInfo|ctx|context|task)$/][callee.property.name=/^(skip|fixme)$/]",
  "CallExpression[callee.object.callee.property.name='info'][callee.property.name=/^(skip|fixme)$/]",
  "CallExpression[callee.name=/^(xit|xtest|xdescribe|fit|fdescribe)$/]",
].map((selector) => ({ selector, message: SKIP_MESSAGE }));

/**
 * Conditional-visibility guards: a state query (isVisible(), count(), …)
 * anywhere inside the test of an if / ternary / loop, or on the left of
 * && / || / ??. Such a branch silently passes when the UI is wrong.
 * `X > .test` is an esquery field selector (the node in X's `test` field);
 * the first form matches the call nested in it, the second the call itself.
 */
const STATE_QUERY =
  "CallExpression[callee.property.name=/^(isVisible|isHidden|count|isEnabled|isDisabled|isChecked|isEditable)$/]";
const GUARD_MESSAGE =
  "No branching on UI state (isVisible/count/isEnabled/…): use a web-first assertion such as await expect(locator).toBeVisible() or .toHaveCount(n).";
const TESTED = ":matches(IfStatement, ConditionalExpression, WhileStatement, DoWhileStatement, ForStatement)";
const GUARD_SELECTORS = [
  `${TESTED} > .test ${STATE_QUERY}`,
  `${TESTED} > ${STATE_QUERY}.test`,
  `LogicalExpression > .left ${STATE_QUERY}`,
  `LogicalExpression > ${STATE_QUERY}.left`,
].map((selector) => ({ selector, message: GUARD_MESSAGE }));

const WAIT_FOR_TIMEOUT = {
  selector: "CallExpression[callee.property.name='waitForTimeout']",
  message: "No waitForTimeout: wait for a condition with a web-first assertion or expect.poll().",
};

// ─── i18n (PLAN §10.1 W0.5, AC14) ────────────────────────────────────────────
// Mode "jsx-only" + an attribute *include* list: flags JSX text and string
// literals rendered as JSX children ({cond && 'Save'}), plus the listed
// user-facing attributes on any element or component. Every other attribute
// (className, data-testid, href, type, id, key, role, event handlers, …) is
// skipped because the include list is exhaustive. "jsx-text-only" would miss
// placeholder/aria-label/title/alt; "all" would flag every string in logic.
// Severity "warn" until integration, when it becomes "error".
const USER_FACING_ATTRIBUTES = [
  "placeholder",
  "aria-label",
  "aria-description",
  "aria-placeholder",
  "aria-roledescription",
  "aria-valuetext",
  "title",
  "alt",
  "label",
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Playwright:
    "playwright-report/**",
    "test-results/**",
  ]),
  // Test files: allow `any` for mocks and test utilities
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // Every test file: no skipped/focused/todo tests.
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "e2e/**/*.ts"],
    rules: {
      "no-restricted-syntax": ["error", ...SKIP_SELECTORS],
    },
  },
  // e2e: no visibility guards, no fixed sleeps (plus the skip ban, repeated).
  {
    files: ["e2e/**/*.ts"],
    rules: {
      "no-restricted-syntax": ["error", ...SKIP_SELECTORS, ...GUARD_SELECTORS, WAIT_FOR_TIMEOUT],
      // No React in e2e: Playwright fixtures call `use(value)`, which is not a hook.
      "react-hooks/rules-of-hooks": "off",
    },
  },
  // e2e specs take test/expect from ./fixtures (counting expect, tytax fixture).
  {
    files: ["e2e/**/*.spec.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@playwright/test",
              message: "Import { test, expect } (and types) from './fixtures' in specs.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["src/**/*.tsx"],
    ignores: ["**/*.test.tsx", "**/__tests__/**"],
    plugins: { i18next },
    rules: {
      "i18next/no-literal-string": [
        "warn",
        { mode: "jsx-only", "jsx-attributes": { include: USER_FACING_ATTRIBUTES } },
      ],
    },
  },
]);

export default eslintConfig;
