/** Markdown renderers for the catalog build's review documents. */
import type { Exercise } from '../../src/contracts/domain';
import type { BuildOutput, NoStationCategory, StationlessEntry } from './catalog-lib';
import { displayName, isTimeTarget, ruleDocs, seededSample, TIME_TARGET } from './catalog-lib';
import { APP_STATIONS } from './station-rules';

const pct = (n: number, d: number) => `${((n / d) * 100).toFixed(1)} %`;
const cell = (s: string | number | undefined) => String(s ?? '').replace(/\|/g, '\\|');

const CATEGORY_TEXT: Record<NoStationCategory, string> = {
  stretch: 'Stretches and mobility (with or without machine assistance).',
  bodyweight: 'Free-standing bodyweight (push-ups, planks, squats, bridges and sit-ups without the bench).',
  ambiguous: 'Machine exercise, but the name does not say which station.',
  'free-weight': 'Free weights (dumbbell, barbell, EZ bar) with no app-level station.',
  'bodyweight-frame': 'Bodyweight on the frame with no app-level station.',
};

const BY_DESIGN_ORDER: readonly NoStationCategory[] = ['stretch', 'bodyweight'];
const UNRESOLVED_ORDER: readonly NoStationCategory[] = ['ambiguous', 'free-weight', 'bodyweight-frame', 'stretch', 'bodyweight'];

function entryTable(rows: readonly StationlessEntry[]): string[] {
  const out = ['| # | Exercise | Id | Pattern | Muscle group |', '|---|---|---|---|---|'];
  rows.forEach((u, i) => out.push(`| ${i + 1} | ${cell(u.name)} | \`${u.id}\` | ${cell(u.pattern)} | ${u.muscleGroup} |`));
  return out;
}

export function renderUnresolved(out: BuildOutput): string {
  const s = out.stats;
  const d = s.sourceTotal;
  const byDesign = out.stationless.filter((u) => u.kind === 'by-design');
  const unresolved = out.stationless.filter((u) => u.kind === 'unresolved');
  const appIds = new Set<string>(APP_STATIONS.map((a) => a.id));
  const appMapped = out.exercises.filter((e) => e.stationId !== undefined && appIds.has(e.stationId));
  const lines: string[] = [
    '# TYTAX station mapping: stations, no station by design, unresolved',
    '',
    'Generated by `npm run catalog:build` (scripts/data/build-catalog.ts). Do not edit by hand.',
    '',
    `Fixed denominator: **${d}** source entries (tytax-autonomous \`full_exercises_final.js\`).`,
    '',
    '| Bucket | Count | Share of 1,436 |',
    '|---|---|---|',
    `| Mapped: station from source metadata (\`t1x-meta\`) | ${s.byProvenance['t1x-meta'] ?? 0} | ${pct(s.byProvenance['t1x-meta'] ?? 0, d)} |`,
    `| Mapped: station from a name rule (\`name-rule:<id>\`) | ${s.byProvenance['name-rule'] ?? 0} | ${pct(s.byProvenance['name-rule'] ?? 0, d)} |`,
    `| Mapped: station from a reviewed hand mapping (\`manual\`) | ${s.byProvenance.manual ?? 0} | ${pct(s.byProvenance.manual ?? 0, d)} |`,
    `| **No station by design** (stretches + free-standing bodyweight) | **${s.noStationByDesign}** | **${pct(s.noStationByDesign, d)}** |`,
    `| **Unresolved** (ambiguous machine moves) | **${s.unresolved}** | **${pct(s.unresolved, d)}** |`,
    `| Excluded: not an exercise (promo/delivery videos) | ${s.excluded} | ${pct(s.excluded, d)} |`,
    '',
    `- Machine-move unresolved: **${s.unresolved} of ${d} = ${pct(s.unresolved, d)}** (AC8 bound: ≤ 5 %).`,
    `- Total without a station (no station by design + unresolved): **${s.stationless} of ${d} = ${pct(s.stationless, d)}**.`,
    `- Of the name-rule mappings, ${appMapped.length} use the app-level stations ${APP_STATIONS.map((a) => `${a.id} (${appMapped.filter((e) => e.stationId === a.id).length})`).join(' and ')}.`,
    '',
    `Source entries with the generic station "Tytax": ${s.genericInSource}. After the build, no catalog entry carries the station "Tytax".`,
    '',
    'Station ids are the `tytax_library.json` STATIONS keys (SMITH, BACK_UPPER, BACK_LOWER, LEG_EXTENSION, LEG_CURL) plus two',
    `app-level stations the library does not have: ${APP_STATIONS.map((a) => `${a.id} ("${a.name}")`).join(', ')}.`,
    'Their `notes` in `src/data/tytax/library.json` start with "App-level addition". The app-level rules run after every machine',
    'rule, so no exercise a machine rule places changes station.',
    '',
    '## Without a station, by cause',
    '',
    '| Kind | Cause | Count | Share of 1,436 |',
    '|---|---|---|---|',
  ];
  const byCause = (kind: string, rows: readonly StationlessEntry[], order: readonly NoStationCategory[]) =>
    order.flatMap((c) => {
      const n = rows.filter((u) => u.category === c).length;
      return n ? [`| ${kind} | ${CATEGORY_TEXT[c]} | ${n} | ${pct(n, d)} |`] : [];
    });
  lines.push(...byCause('No station by design', byDesign, BY_DESIGN_ORDER), ...byCause('Unresolved', unresolved, UNRESOLVED_ORDER), '');
  for (const c of BY_DESIGN_ORDER) {
    const rows = byDesign.filter((u) => u.category === c);
    if (rows.length) lines.push(`## No station by design: ${CATEGORY_TEXT[c]} (${rows.length})`, '', ...entryTable(rows), '');
  }
  for (const c of UNRESOLVED_ORDER) {
    const rows = unresolved.filter((u) => u.category === c);
    if (rows.length) lines.push(`## Unresolved: ${CATEGORY_TEXT[c]} (${rows.length})`, '', ...entryTable(rows), '');
  }
  lines.push(`## Mapped to an app-level station (${appMapped.length})`, '', '| # | Exercise | Id | Station | Provenance |', '|---|---|---|---|---|');
  appMapped.forEach((e, i) => lines.push(`| ${i + 1} | ${cell(e.name)} | \`${e.id}\` | ${e.stationId} | \`${e.stationProvenance}\` |`));
  lines.push('', '## Excluded (not exercises)', '', '| # | Source name | Rule | Why |', '|---|---|---|---|');
  out.excluded.forEach((x, i) => lines.push(`| ${i + 1} | ${cell(displayName(x.name))} | ${x.ruleId} | ${x.why} |`));
  lines.push('', '## Station rules (first match wins)', '', '| Rule | Station | Why |', '|---|---|---|');
  for (const r of ruleDocs()) lines.push(`| \`name-rule:${r.id}\` | ${r.station} | ${cell(r.why)} |`);
  lines.push('');
  return lines.join('\n');
}

/** Time-measured exercises (`measure: 'time'`) of every chunk, grouped by modality. */
export function renderTimeMeasured(chunks: ReadonlyArray<{ label: string; exercises: readonly Exercise[] }>): string {
  const counts = chunks.map((c) => ({ label: c.label, rows: c.exercises.filter((e) => e.measure === 'time') }));
  const total = counts.reduce((n, c) => n + c.rows.length, 0);
  const lines = [
    '# Time-measured exercises (`measure: \'time\'`)',
    '',
    'Generated by `npm run catalog:build`. Do not edit by hand.',
    '',
    'An exercise is time-measured when its `defaultReps` is a pure time target',
    `(\`isTimeTarget\` in scripts/data/catalog-lib.ts: \`/${TIME_TARGET.source}/${TIME_TARGET.flags}\`,`,
    'e.g. `20-40s`, `30 sec`, `1-2 min`, `40s hold`). The TYTAX build tags them; bodyweight and kettlebell are tagged by hand',
    'in `src/data/{bodyweight,kettlebell}/exercises.ts`, and the data-integrity test checks all three against `isTimeTarget`.',
    '',
    '| Chunk | Time-measured | Of |',
    '|---|---|---|',
    ...counts.map((c, i) => `| ${c.label} | ${c.rows.length} | ${chunks[i].exercises.length} |`),
    `| **Total** | **${total}** | **${chunks.reduce((n, c) => n + c.exercises.length, 0)}** |`,
    '',
  ];
  for (const c of counts) {
    lines.push(`## ${c.label} (${c.rows.length})`, '', '| # | Id | Exercise | defaultReps |', '|---|---|---|---|');
    c.rows.forEach((e, i) => lines.push(`| ${i + 1} | \`${e.id}\` | ${cell(e.name)} | ${cell(e.defaultReps)} |`));
    lines.push('');
  }
  const mismatched = chunks.flatMap((c) => c.exercises.filter((e) => (e.measure === 'time') !== isTimeTarget(e.defaultReps)));
  if (mismatched.length) lines.push(`**Mismatch with isTimeTarget: ${mismatched.map((e) => e.id).join(', ')}**`, '');
  return lines.join('\n');
}

export function renderSample(out: BuildOutput): string {
  // App-level stations (FRAME, FREE_WEIGHT) are listed in full in station-unresolved.md, so the machine sample stays stable.
  const appIds = new Set<string>(APP_STATIONS.map((a) => a.id));
  const remapped = out.exercises.filter((e) => e.stationProvenance && e.stationProvenance !== 't1x-meta' && !appIds.has(e.stationId ?? ''));
  const sample = seededSample(remapped, 50, 42);
  const lines = [
    '# TYTAX station mapping: review sample',
    '',
    'Generated by `npm run catalog:build`. 50 entries drawn with seed 42 (mulberry32, Fisher–Yates over ids) from the',
    `${remapped.length} exercises whose station came from a name rule or a hand mapping (the source said only "Tytax").`,
    'Morning review: mark each row OK or give the right station.',
    'The app-level FRAME and FREE_WEIGHT mappings are not sampled: station-unresolved.md lists all of them.',
    '',
    '| # | Exercise | Station | Attachments | Provenance | Review |',
    '|---|---|---|---|---|---|',
    ...sample.map((e, i) => `| ${i + 1} | ${cell(e.name)} | ${e.stationId} | ${(e.attachmentIds ?? []).join(', ') || '–'} | \`${e.stationProvenance}\` | |`),
    '',
  ];
  return lines.join('\n');
}

export function renderReconciliation(out: BuildOutput, previousIds: ReadonlySet<string>): string {
  const now = new Set(out.exercises.map((e) => e.id));
  const dropped = [...previousIds].filter((id) => !now.has(id)).sort();
  const added = [...now].filter((id) => !previousIds.has(id)).sort();
  const excludedById = new Map(out.excluded.map((x) => [x.id, x]));
  const lines = [
    '# TYTAX catalog reconciliation: tytax-autonomous (1,436) vs new_tytax (1,420) vs v2',
    '',
    'Generated by `npm run catalog:build`.',
    '',
    `- tytax-autonomous source entries: ${out.stats.sourceTotal}`,
    `- new_tytax (pre-v2) catalog entries: ${previousIds.size}`,
    `- v2 catalog entries: ${out.stats.catalog} (= ${out.stats.sourceTotal} − ${out.stats.excluded} non-exercises)`,
    `- ids kept from new_tytax: ${[...previousIds].filter((id) => now.has(id)).length}; ids are stable (scripts/data/id-registry.json)`,
    '',
    `## In new_tytax, not in v2 (${dropped.length})`,
    '',
    '| Id | Why |',
    '|---|---|',
    ...dropped.map((id) => `| \`${id}\` | ${excludedById.get(id)?.why ?? 'not in source'} |`),
    '',
    `## In v2, not in new_tytax (${added.length})`,
    '',
    added.length ? '| Id |\n|---|' : 'None.',
    ...added.map((id) => `| \`${id}\` |`),
    '',
    `## In the source, excluded from both (${out.excluded.filter((x) => !previousIds.has(x.id)).length})`,
    '',
    '| Source name | Why |',
    '|---|---|',
    ...out.excluded.filter((x) => !previousIds.has(x.id)).map((x) => `| ${cell(displayName(x.name))} | ${x.why} |`),
    '',
  ];
  return lines.join('\n');
}
