/** Markdown renderers for the catalog build's review documents. */
import type { BuildOutput, UnresolvedCategory } from './catalog-lib';
import { displayName, ruleDocs, seededSample } from './catalog-lib';

const pct = (n: number, d: number) => `${((n / d) * 100).toFixed(1)} %`;
const cell = (s: string | number | undefined) => String(s ?? '').replace(/\|/g, '\\|');

const CATEGORY_TEXT: Record<UnresolvedCategory, string> = {
  'free-weight': 'Free weights (dumbbell, barbell, EZ bar): no T1-X station in `tytax_library.json`.',
  'bodyweight-frame': 'Bodyweight on the frame (pull-up/dip handles, hanging, roman chair): the library has no frame station.',
  bodyweight: 'Pure bodyweight (sit-ups, push-ups, planks, bridges, squats).',
  stretch: 'Stretches and mobility without machine resistance.',
  ambiguous: 'Machine exercise, but the name does not say which station.',
};

export function renderUnresolved(out: BuildOutput): string {
  const s = out.stats;
  const d = s.sourceTotal;
  const cats = Object.keys(CATEGORY_TEXT) as UnresolvedCategory[];
  const lines: string[] = [
    '# TYTAX station mapping: unresolved exercises',
    '',
    'Generated by `npm run catalog:build` (scripts/data/build-catalog.ts). Do not edit by hand.',
    '',
    `Fixed denominator: **${d}** source entries (tytax-autonomous \`full_exercises_final.js\`).`,
    '',
    '| Bucket | Count | Share of 1,436 |',
    '|---|---|---|',
    `| Station from source metadata (\`t1x-meta\`) | ${s.byProvenance['t1x-meta'] ?? 0} | ${pct(s.byProvenance['t1x-meta'] ?? 0, d)} |`,
    `| Station from a name rule (\`name-rule:<id>\`) | ${s.byProvenance['name-rule'] ?? 0} | ${pct(s.byProvenance['name-rule'] ?? 0, d)} |`,
    `| Station from a reviewed hand mapping (\`manual\`) | ${s.byProvenance.manual ?? 0} | ${pct(s.byProvenance.manual ?? 0, d)} |`,
    `| **Unresolved** (no station) | **${s.unresolved}** | **${pct(s.unresolved, d)}** |`,
    `| Excluded: not an exercise (promo/delivery videos) | ${s.excluded} | ${pct(s.excluded, d)} |`,
    '',
    `Source entries with the generic station "Tytax": ${s.genericInSource}. After the build, no catalog entry carries the station "Tytax".`,
    '',
    '## Unresolved by cause',
    '',
    '| Cause | Count | Share of 1,436 |',
    '|---|---|---|',
    ...cats.map((c) => {
      const n = out.unresolved.filter((u) => u.category === c).length;
      return `| ${CATEGORY_TEXT[c]} | ${n} | ${pct(n, d)} |`;
    }),
    '',
    'Station ids come only from `tytax_library.json` STATIONS (SMITH, BACK_UPPER, BACK_LOWER, LEG_EXTENSION, LEG_CURL).',
    'Mapping the free-weight, frame and stretch entries needs a station the library does not have; see the G1 report for the proposed fix.',
    '',
  ];
  for (const c of cats) {
    const rows = out.unresolved.filter((u) => u.category === c);
    if (!rows.length) continue;
    lines.push(`## ${CATEGORY_TEXT[c]} (${rows.length})`, '', '| # | Exercise | Id | Pattern | Muscle group |', '|---|---|---|---|---|');
    rows.forEach((u, i) => lines.push(`| ${i + 1} | ${cell(u.name)} | \`${u.id}\` | ${cell(u.pattern)} | ${u.muscleGroup} |`));
    lines.push('');
  }
  lines.push('## Excluded (not exercises)', '', '| # | Source name | Rule | Why |', '|---|---|---|---|');
  out.excluded.forEach((x, i) => lines.push(`| ${i + 1} | ${cell(displayName(x.name))} | ${x.ruleId} | ${x.why} |`));
  lines.push('', '## Station rules (first match wins)', '', '| Rule | Station | Why |', '|---|---|---|');
  for (const r of ruleDocs()) lines.push(`| \`name-rule:${r.id}\` | ${r.station} | ${cell(r.why)} |`);
  lines.push('');
  return lines.join('\n');
}

export function renderSample(out: BuildOutput): string {
  const remapped = out.exercises.filter((e) => e.stationProvenance && e.stationProvenance !== 't1x-meta');
  const sample = seededSample(remapped, 50, 42);
  const lines = [
    '# TYTAX station mapping: review sample',
    '',
    'Generated by `npm run catalog:build`. 50 entries drawn with seed 42 (mulberry32, Fisher–Yates over ids) from the',
    `${remapped.length} exercises whose station came from a name rule or a hand mapping (the source said only "Tytax").`,
    'Morning review: mark each row OK or give the right station.',
    '',
    '| # | Exercise | Station | Attachments | Provenance | Review |',
    '|---|---|---|---|---|---|',
    ...sample.map((e, i) => `| ${i + 1} | ${cell(e.name)} | ${e.stationId} | ${(e.attachmentIds ?? []).join(', ') || '–'} | \`${e.stationProvenance}\` | |`),
    '',
  ];
  return lines.join('\n');
}

export function renderReconciliation(out: BuildOutput, previousIds: ReadonlySet<string>): string {
  const now = new Set(out.exercises.map((e) => e.id));
  const dropped = [...previousIds].filter((id) => !now.has(id)).sort();
  const added = [...now].filter((id) => !previousIds.has(id)).sort();
  const excludedById = new Map(out.excluded.map((x) => [x.id, x]));
  const lines = [
    '# TYTAX catalog reconciliation: tytax-autonomous (1,436) vs new_tytax (1,420) vs v2',
    '',
    'Generated by `npm run catalog:build`.',
    '',
    `- tytax-autonomous source entries: ${out.stats.sourceTotal}`,
    `- new_tytax (pre-v2) catalog entries: ${previousIds.size}`,
    `- v2 catalog entries: ${out.stats.catalog} (= ${out.stats.sourceTotal} − ${out.stats.excluded} non-exercises)`,
    `- ids kept from new_tytax: ${[...previousIds].filter((id) => now.has(id)).length}; ids are stable (scripts/data/id-registry.json)`,
    '',
    `## In new_tytax, not in v2 (${dropped.length})`,
    '',
    '| Id | Why |',
    '|---|---|',
    ...dropped.map((id) => `| \`${id}\` | ${excludedById.get(id)?.why ?? 'not in source'} |`),
    '',
    `## In v2, not in new_tytax (${added.length})`,
    '',
    added.length ? '| Id |\n|---|' : 'None.',
    ...added.map((id) => `| \`${id}\` |`),
    '',
    `## In the source, excluded from both (${out.excluded.filter((x) => !previousIds.has(x.id)).length})`,
    '',
    '| Source name | Why |',
    '|---|---|',
    ...out.excluded.filter((x) => !previousIds.has(x.id)).map((x) => `| ${cell(displayName(x.name))} | ${x.why} |`),
    '',
  ];
  return lines.join('\n');
}
