"""Wave 2: regenerate G4 request modules from G1/G5 request tables and G3's live string tables.
Inputs: g1/docs/v2/requests/G1-i18n.md, g5/docs/v2/requests/G5-i18n.md, g3_tables.json (extract_g3.ts via tsx).
Outputs: src/lib/i18n/modules/{requests,g3Tools,g3Picker,g3Workout,g5Auth}.ts"""
import json, re, sys
ROOT='/home/tomi/Projects/tytax-v2'; S=sys.argv[1] if len(sys.argv)>1 else '.'
MOD=ROOT+'/g4/src/lib/i18n/modules/'
def md(path):
    rows=[];order=None
    for line in open(path):
        if not line.startswith('|'): continue
        c=[x.strip() for x in line.strip().strip('|').split('|')]
        if c[0].lower()=='key': order=[x.lower() for x in c]; continue
        if set(''.join(c))<=set('-: '): continue
        rows.append((c[0].strip('`').split(' ')[0], c[order.index('en')], c[order.index('hr')]))
    return rows
g3=json.load(open(S+'/g3_tables.json'))
def g3rows(f):
    t=list(g3[f].values())[0]; return [(k,t['en'][k],t['hr'][k]) for k in t['en']]
TABLE={'finish':'FINISH_STRINGS','muscles':'MUSCLE_STRINGS','picker':'PICKER_STRINGS','sets':'SETS_STRINGS','start':'START_STRINGS','timer':'TIMER_STRINGS','tools':'TOOLS_STRINGS','setup':'SETUP_STRINGS','time':'TIME_STRINGS'}
PATH={'tools':'src/components/tools/tools-strings.ts'}
def src(f): return PATH.get(f, f'src/components/workout/strings/{f}.ts') + f' ({TABLE[f]})'
modules={
 'requests':('G1 request table: docs/v2/requests/G1-i18n.md (v2-g1).',[('G1-i18n.md',md(ROOT+'/g1/docs/v2/requests/G1-i18n.md'))]),
 'g3Tools':("G3's local tables, tools + rest timer (docs/v2/requests/G3-i18n.md).",[(src(f),g3rows(f)) for f in ('tools','timer')]),
 'g3Picker':("G3's local tables, exercise picker/swap + muscle names (docs/v2/requests/G3-i18n.md).",[(src(f),g3rows(f)) for f in ('picker','muscles')]),
 'g3Workout':("G3's local tables, start page, sets/cards, finish/PR (docs/v2/requests/G3-i18n.md).",[(src(f),g3rows(f)) for f in ('start','sets','finish')]),
 'g3Session':("G3's local tables, Wave 2 machine setup + time-measured sets.",[(src(f),g3rows(f)) for f in ('setup','time')]),
 'g5Auth':('G5 request table: docs/v2/requests/G5-i18n.md (v2-g5); dotted keys as G5 specified.',[('G5-i18n.md',md(ROOT+'/g5/docs/v2/requests/G5-i18n.md'))]),
}
q=lambda s:"'"+s.replace('\\','\\\\').replace("'","\\'")+"'"
qk=lambda k:k if re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*',k) else q(k)
seen={}
for name,(doc,sections) in modules.items():
    def block(i):
        out=[]
        for label,rows in sections:
            out.append(f'  // {label}')
            for r in rows: out.append(f'  {qk(r[0])}: {q(r[i])},')
        return '\n'.join(out)
    for label,rows in sections:
        for r in rows:
            assert r[0] not in seen, (r[0], seen.get(r[0]), name); seen[r[0]]=name
    text=f"""// {doc}
// Generated by G4 (scratchpad merge_i18n_w2.py); edit the source table, then re-merge.
export const {name}En = {{
{block(1)}
}} as const;

export const {name}Hr: Record<keyof typeof {name}En, string> = {{
{block(2)}
}};
"""
    open(MOD+name+'.ts','w').write(text)
    print(name, sum(len(r) for _,r in sections), 'keys', text.count('\n'), 'lines')
print('total', len(seen))
