// TYTAX exercise data, generated by `npm run catalog:build` (scripts/data/build-catalog.ts):
// 1,404 exercises from the 1,436-entry tytax-autonomous source. UI code must use the lazy
// catalog (`@/lib/catalog`) instead of importing this module.
import type { Exercise } from '@/types';
import rawData from './exercises.json';

export const TYTAX_EXERCISES = rawData as unknown as Exercise[];

export default TYTAX_EXERCISES;
