import type { ProgramTemplate } from '@/contracts/domain';
import originalPlan from './original-plan.json';
import { TYTAX_BALANCED_6DAY, TYTAX_ELITE_V3 } from './presets-balanced';

export { TYTAX_BALANCED_6DAY, TYTAX_ELITE_V3 };

/** Stable preset id of the recovery-balanced 6-day split: the default TYTAX program since 2026-09-27. */
export const TYTAX_BALANCED_6DAY_PRESET_ID = 'tytax-balanced-6day';

/**
 * The original tytax-autonomous 6-day split (INITIAL_PLAN: Upper A/B/C,
 * Lower A/B/C, Rest Day), generated by `npm run catalog:build` with every
 * exercise resolved to a catalog id. Kept unchanged as the historical plan;
 * the default is now the balanced split in `presets-balanced.ts`.
 */
export const TYTAX_ORIGINAL_6DAY_PRESET_ID = 'tytax-original-6day';
// Generated JSON (scripts/data/catalog-lib.ts `originalPlan`); shape checked by the data-integrity test.
export const TYTAX_ORIGINAL_6DAY = originalPlan as unknown as ProgramTemplate;

/** Stable preset id of the Tytax Elite program (v3.1 since 2026-09-27; the id is unchanged so installs keep matching). */
export const TYTAX_ELITE_V3_PRESET_ID = 'tytax-elite-v3';

export const TYTAX_PRESETS: ProgramTemplate[] = [TYTAX_BALANCED_6DAY, TYTAX_ORIGINAL_6DAY, TYTAX_ELITE_V3];
