import type { ProgramTemplate } from '@/contracts/domain';
import originalPlan from './original-plan.json';

/**
 * The original tytax-autonomous 6-day split (INITIAL_PLAN: Upper A/B/C,
 * Lower A/B/C, Rest Day), generated by `npm run catalog:build` with every
 * exercise resolved to a catalog id. The default TYTAX program.
 */
export const TYTAX_ORIGINAL_6DAY_PRESET_ID = 'tytax-original-6day';
// Generated JSON (scripts/data/catalog-lib.ts `originalPlan`); shape checked by the data-integrity test.
export const TYTAX_ORIGINAL_6DAY = originalPlan as unknown as ProgramTemplate;

/** Stable preset id of the Tytax Elite v3.0 program (new_tytax's 6-day variant). */
export const TYTAX_ELITE_V3_PRESET_ID = 'tytax-elite-v3';

// The classic Tytax Elite v3.0 - 6-day + 1 rest rotation
export const TYTAX_ELITE_V3: ProgramTemplate = {
  presetId: TYTAX_ELITE_V3_PRESET_ID,
  name: 'Tytax Elite v3.0',
  splitType: 'custom',
  frequency: 6,
  periodizationType: 'none',
  sessionOrder: ['Upper A', 'Lower A', 'Upper B', 'Lower B', 'Upper C', 'Lower C', 'Rest'],
  modalitiesUsed: ['tytax'],
  isPreset: true,
  currentSessionIndex: 0,
  sessions: [
    {
      id: 'preset-tytax-upper-a',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Upper A',
      dayIndex: 0,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-flat-bench-press', exerciseName: 'Smith Flat Bench Press', modality: 'tytax', sets: 4, reps: '6-10', restSeconds: 120 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-wide-grip-lat-pulldown', exerciseName: 'Upper Pulley Wide-Grip Lat Pulldown', modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_smith-machine_seated-smith-shoulder-press', exerciseName: 'Seated Smith Shoulder Press', modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-standing-cable-curl-straight-bar', exerciseName: 'Lower Pulley Standing Cable Curl (straight bar)', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-triceps-pushdown-v-bar', exerciseName: 'Upper Pulley Triceps Pushdown (V-bar)', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-face-pull-rope', exerciseName: 'Upper Pulley Face Pull (rope)', modality: 'tytax', sets: 3, reps: '15-20', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-lower-a',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Lower A',
      dayIndex: 1,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-back-squat', exerciseName: 'Smith Back Squat', modality: 'tytax', sets: 4, reps: '6-10', restSeconds: 180 },
        { exerciseId: 'tytax_leg-extension_seated-leg-extension', exerciseName: 'Seated Leg Extension', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 90 },
        { exerciseId: 'tytax_leg-curl_seated-leg-curl', exerciseName: 'Seated Leg Curl', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-cable-pull-through', exerciseName: 'Lower Pulley Cable Pull-Through', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-standing-calf-raise', exerciseName: 'Smith Standing Calf Raise', modality: 'tytax', sets: 4, reps: '15-20', restSeconds: 60 },
        { exerciseId: 'tytax_tytax_cable-crunch', exerciseName: 'Cable Crunch', modality: 'tytax', sets: 3, reps: '12-20', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-upper-b',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Upper B',
      dayIndex: 2,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-incline-bench-press', exerciseName: 'Smith Incline Bench Press', modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-close-grip-lat-pulldown', exerciseName: 'Upper Pulley Close-Grip Lat Pulldown', modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-single-arm-lateral-raise', exerciseName: 'Lower Pulley Single-Arm Lateral Raise', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-rope-hammer-curl', exerciseName: 'Lower Pulley Rope Hammer Curl', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-rope-triceps-pushdown', exerciseName: 'Upper Pulley Rope Triceps Pushdown', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_tytax_rear-delt-fly', exerciseName: 'Rear Delt Fly', modality: 'tytax', sets: 3, reps: '15-20', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-lower-b',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Lower B',
      dayIndex: 3,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-front-squat-cross-arm', exerciseName: 'Smith Front Squat (cross-arm)', modality: 'tytax', sets: 4, reps: '6-10', restSeconds: 180 },
        { exerciseId: 'tytax_leg-extension_seated-leg-extension', exerciseName: 'Seated Leg Extension', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 90 },
        { exerciseId: 'tytax_leg-curl_seated-leg-curl', exerciseName: 'Seated Leg Curl', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 90 },
        { exerciseId: 'tytax_smith-machine_smith-hip-thrust', exerciseName: 'Smith Hip Thrust', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 90 },
        { exerciseId: 'tytax_tytax_sled-seated-calf-raise', exerciseName: 'Sled Seated Calf Raise', modality: 'tytax', sets: 4, reps: '15-20', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-pallof-press-anti-rotation-hold', exerciseName: 'Lower Pulley Pallof Press (anti-rotation hold)', modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-upper-c',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Upper C',
      dayIndex: 4,
      exercises: [
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-high-to-low-single-arm-cable-fly', exerciseName: 'Upper Pulley High-to-Low Single-Arm Cable Fly', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 90 },
        { exerciseId: 'tytax_tytax_seated-cable-row', exerciseName: 'Seated Cable Row', modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_tytax_cable-overhead-triceps-extension', exerciseName: 'Cable Overhead Triceps Extension', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_tytax_cable-preacher-curl', exerciseName: 'Cable Preacher Curl', modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_standing-smith-shrug', exerciseName: 'Standing Smith Shrug', modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_tytax_standing-cable-y-raise', exerciseName: 'Standing Cable Y Raise', modality: 'tytax', sets: 3, reps: '15-20', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-lower-c',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Lower C',
      dayIndex: 5,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-hack-squat-feet-forward', exerciseName: 'Smith Hack Squat (feet forward)', modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 150 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-single-arm-lateral-raise', exerciseName: 'Lower Pulley Single-Arm Lateral Raise', modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-bayesian-curl-cable-behind-body', exerciseName: 'Lower Pulley Bayesian Curl (cable behind body)', modality: 'tytax', sets: 3, reps: '10-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-single-arm-triceps-pushdown', exerciseName: 'Upper Pulley Single-Arm Triceps Pushdown', modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-low-to-high-woodchop', exerciseName: 'Lower Pulley Low-to-High Woodchop', modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_tytax_cable-wrist-curl', exerciseName: 'Cable Wrist Curl', modality: 'tytax', sets: 3, reps: '15-20', restSeconds: 45 },
      ],
    },
    {
      id: 'preset-tytax-rest',
      programId: '', // Intentional: presets don't have IDs until installed
      name: 'Rest',
      dayIndex: 6,
      exercises: [],
      isRest: true,
    },
  ],
};

export const TYTAX_PRESETS: ProgramTemplate[] = [TYTAX_ORIGINAL_6DAY, TYTAX_ELITE_V3];
