// GENERATED by scripts/data/gen-balanced-presets.mjs; edit the spec there, not this file.
import type { ProgramTemplate } from '@/contracts/domain';

/**
 * Recovery-balanced 6-day upper/lower split (2026-09-27).
 * - Upper and lower alternate, so every muscle gets 48 h before it is trained again, and no muscle
 *   takes 3+ fractional sets on two consecutive days (tested in data-integrity).
 * - Intensity undulates A heavy (5-10 reps, long rests) > B moderate (8-15) > C light (10-20, short rests):
 *   the lightest two sessions come right before the rest day.
 * - One heavy axial squat (Lower A) and one heavy hinge (Lower B) per week; Lower C is unilateral.
 * - Weekly fractional sets per muscle sit in 6-14 (see the data-integrity bounds).
 */
export const TYTAX_BALANCED_6DAY: ProgramTemplate = {
  presetId: 'tytax-balanced-6day',
  name: 'TYTAX 6-Day Balanced',
  splitType: 'upper_lower',
  frequency: 6,
  periodizationType: 'none',
  sessionOrder: ['Upper A', 'Lower A', 'Upper B', 'Lower B', 'Upper C', 'Lower C', 'Rest'],
  modalitiesUsed: ['tytax'],
  isPreset: true,
  currentSessionIndex: 0,
  sessions: [
    {
      id: 'preset-tytax-bal-upper-a',
      programId: '', // presets get an id when installed
      name: 'Upper A',
      dayIndex: 0,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-flat-bench-press', exerciseName: "Smith Flat Bench Press", modality: 'tytax', sets: 4, reps: '5-8', restSeconds: 150 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-underhand-lat-pulldown', exerciseName: "Upper Pulley Underhand Lat Pulldown", modality: 'tytax', sets: 3, reps: '6-10', restSeconds: 120 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-chest-supported-row-bench-incline', exerciseName: "Lower Pulley Chest-Supported Row (bench incline)", modality: 'tytax', sets: 3, reps: '8-10', restSeconds: 120 },
        { exerciseId: 'tytax_smith-machine_smith-seated-shoulder-press', exerciseName: "Smith Seated Shoulder Press", modality: 'tytax', sets: 3, reps: '6-10', restSeconds: 120 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-lean-away-lateral-raise', exerciseName: "Lower Pulley Lean-Away Lateral Raise", modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-face-pull-rope', exerciseName: "Upper Pulley Face Pull (rope)", modality: 'tytax', sets: 2, reps: '15-20', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-bal-lower-a',
      programId: '', // presets get an id when installed
      name: 'Lower A',
      dayIndex: 1,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-back-squat', exerciseName: "Smith Back Squat", modality: 'tytax', sets: 4, reps: '5-8', restSeconds: 180 },
        { exerciseId: 'tytax_leg-curl_seated-leg-curl', exerciseName: "Seated Leg Curl", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_smith-machine_smith-hip-thrust', exerciseName: "Smith Hip Thrust", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_smith-machine_smith-standing-calf-raise', exerciseName: "Smith Standing Calf Raise", modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-kneeling-cable-crunch', exerciseName: "Upper Pulley Kneeling Cable Crunch", modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-bal-upper-b',
      programId: '', // presets get an id when installed
      name: 'Upper B',
      dayIndex: 2,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-incline-bench-press', exerciseName: "Smith Incline Bench Press", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-neutral-grip-lat-pulldown-v-handle', exerciseName: "Upper Pulley Neutral-Grip Lat Pulldown (V-handle)", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-wide-grip-seated-cable-row', exerciseName: "Lower Pulley Wide-Grip Seated Cable Row", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-single-arm-lateral-raise', exerciseName: "Lower Pulley Single-Arm Lateral Raise", modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-bayesian-curl-cable-behind-body', exerciseName: "Lower Pulley Bayesian Curl (cable behind body)", modality: 'tytax', sets: 3, reps: '10-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-overhead-triceps-extension-rope', exerciseName: "Upper Pulley Overhead Triceps Extension (rope)", modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-bal-lower-b',
      programId: '', // presets get an id when installed
      name: 'Lower B',
      dayIndex: 3,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-romanian-deadlift-rdl', exerciseName: "Smith Romanian Deadlift (RDL)", modality: 'tytax', sets: 3, reps: '6-10', restSeconds: 150 },
        { exerciseId: 'tytax_smith-machine_smith-lying-leg-press-bench-setup', exerciseName: "Smith Lying Leg Press (bench setup)", modality: 'tytax', sets: 3, reps: '10-12', restSeconds: 120 },
        { exerciseId: 'tytax_leg-extension_seated-leg-extension', exerciseName: "Seated Leg Extension", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-seated-calf-raise-bench-setup', exerciseName: "Smith Seated Calf Raise (bench setup)", modality: 'tytax', sets: 3, reps: '12-20', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-pallof-press-anti-rotation-hold', exerciseName: "Lower Pulley Pallof Press (anti-rotation hold)", modality: 'tytax', sets: 2, reps: '10-12/side', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-bal-upper-c',
      programId: '', // presets get an id when installed
      name: 'Upper C',
      dayIndex: 4,
      exercises: [
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-low-to-high-single-arm-cable-fly', exerciseName: "Lower Pulley Low-to-High Single-Arm Cable Fly", modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-single-arm-kneeling-lat-pulldown', exerciseName: "Upper Pulley Single-Arm Kneeling Lat Pulldown", modality: 'tytax', sets: 3, reps: '10-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-rope-row-elbows-high-for-rear-delts', exerciseName: "Lower Pulley Rope Row (elbows high for rear delts)", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-single-arm-lateral-raise', exerciseName: "Lower Pulley Single-Arm Lateral Raise", modality: 'tytax', sets: 3, reps: '15-20/side', restSeconds: 45 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-preacher-curl-bench-support', exerciseName: "Lower Pulley Preacher Curl (bench support)", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-rope-triceps-pushdown', exerciseName: "Upper Pulley Rope Triceps Pushdown", modality: 'tytax', sets: 2, reps: '12-15', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-bal-lower-c',
      programId: '', // presets get an id when installed
      name: 'Lower C',
      dayIndex: 5,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-bulgarian-split-squat', exerciseName: "Smith Bulgarian Split Squat", modality: 'tytax', sets: 2, reps: '10-12/leg', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-kneeling-hamstring-curl-ankle-strap', exerciseName: "Lower Pulley Kneeling Hamstring Curl (ankle strap)", modality: 'tytax', sets: 3, reps: '10-15/leg', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-single-leg-hip-thrust', exerciseName: "Smith Single-Leg Hip Thrust", modality: 'tytax', sets: 2, reps: '10-15/leg', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-single-leg-standing-calf-raise', exerciseName: "Smith Single-Leg Standing Calf Raise", modality: 'tytax', sets: 2, reps: '12-20/leg', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-high-to-low-woodchop', exerciseName: "Upper Pulley High-to-Low Woodchop", modality: 'tytax', sets: 2, reps: '10-15/side', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-bal-rest',
      programId: '',
      name: 'Rest',
      dayIndex: 6,
      exercises: [],
      isRest: true,
    },
  ],
};

/** Elite v3.1: the balanced skeleton at top-of-range volume (replaces v3.0, which trained arms and delts on back-to-back days). */
export const TYTAX_ELITE_V3: ProgramTemplate = {
  presetId: 'tytax-elite-v3',
  name: 'Tytax Elite v3.1',
  splitType: 'upper_lower',
  frequency: 6,
  periodizationType: 'none',
  sessionOrder: ['Upper A', 'Lower A', 'Upper B', 'Lower B', 'Upper C', 'Lower C', 'Rest'],
  modalitiesUsed: ['tytax'],
  isPreset: true,
  currentSessionIndex: 0,
  sessions: [
    {
      id: 'preset-tytax-upper-a',
      programId: '', // presets get an id when installed
      name: 'Upper A',
      dayIndex: 0,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-flat-bench-press', exerciseName: "Smith Flat Bench Press", modality: 'tytax', sets: 4, reps: '5-8', restSeconds: 150 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-underhand-lat-pulldown', exerciseName: "Upper Pulley Underhand Lat Pulldown", modality: 'tytax', sets: 4, reps: '6-10', restSeconds: 120 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-chest-supported-row-bench-incline', exerciseName: "Lower Pulley Chest-Supported Row (bench incline)", modality: 'tytax', sets: 3, reps: '8-10', restSeconds: 120 },
        { exerciseId: 'tytax_smith-machine_smith-seated-shoulder-press', exerciseName: "Smith Seated Shoulder Press", modality: 'tytax', sets: 3, reps: '6-10', restSeconds: 120 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-lean-away-lateral-raise', exerciseName: "Lower Pulley Lean-Away Lateral Raise", modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-face-pull-rope', exerciseName: "Upper Pulley Face Pull (rope)", modality: 'tytax', sets: 3, reps: '15-20', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-lower-a',
      programId: '', // presets get an id when installed
      name: 'Lower A',
      dayIndex: 1,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-back-squat', exerciseName: "Smith Back Squat", modality: 'tytax', sets: 4, reps: '5-8', restSeconds: 180 },
        { exerciseId: 'tytax_leg-curl_seated-leg-curl', exerciseName: "Seated Leg Curl", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_smith-machine_smith-hip-thrust', exerciseName: "Smith Hip Thrust", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_smith-machine_smith-standing-calf-raise', exerciseName: "Smith Standing Calf Raise", modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-kneeling-cable-crunch', exerciseName: "Upper Pulley Kneeling Cable Crunch", modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
        { exerciseId: 'tytax_leg-extension_seated-leg-extension', exerciseName: "Seated Leg Extension", modality: 'tytax', sets: 2, reps: '12-15', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-upper-b',
      programId: '', // presets get an id when installed
      name: 'Upper B',
      dayIndex: 2,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-incline-bench-press', exerciseName: "Smith Incline Bench Press", modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 120 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-neutral-grip-lat-pulldown-v-handle', exerciseName: "Upper Pulley Neutral-Grip Lat Pulldown (V-handle)", modality: 'tytax', sets: 4, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-wide-grip-seated-cable-row', exerciseName: "Lower Pulley Wide-Grip Seated Cable Row", modality: 'tytax', sets: 3, reps: '8-12', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-single-arm-lateral-raise', exerciseName: "Lower Pulley Single-Arm Lateral Raise", modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-bayesian-curl-cable-behind-body', exerciseName: "Lower Pulley Bayesian Curl (cable behind body)", modality: 'tytax', sets: 3, reps: '10-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-overhead-triceps-extension-rope', exerciseName: "Upper Pulley Overhead Triceps Extension (rope)", modality: 'tytax', sets: 3, reps: '10-15', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-lower-b',
      programId: '', // presets get an id when installed
      name: 'Lower B',
      dayIndex: 3,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-romanian-deadlift-rdl', exerciseName: "Smith Romanian Deadlift (RDL)", modality: 'tytax', sets: 4, reps: '6-10', restSeconds: 150 },
        { exerciseId: 'tytax_smith-machine_smith-lying-leg-press-bench-setup', exerciseName: "Smith Lying Leg Press (bench setup)", modality: 'tytax', sets: 4, reps: '10-12', restSeconds: 120 },
        { exerciseId: 'tytax_leg-extension_seated-leg-extension', exerciseName: "Seated Leg Extension", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-seated-calf-raise-bench-setup', exerciseName: "Smith Seated Calf Raise (bench setup)", modality: 'tytax', sets: 3, reps: '12-20', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-pallof-press-anti-rotation-hold', exerciseName: "Lower Pulley Pallof Press (anti-rotation hold)", modality: 'tytax', sets: 2, reps: '10-12/side', restSeconds: 60 },
        { exerciseId: 'tytax_leg-curl_seated-leg-curl-2s-squeeze-slow-eccentric', exerciseName: "Seated Leg Curl (2s squeeze + slow eccentric)", modality: 'tytax', sets: 2, reps: '10-12', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-upper-c',
      programId: '', // presets get an id when installed
      name: 'Upper C',
      dayIndex: 4,
      exercises: [
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-low-to-high-single-arm-cable-fly', exerciseName: "Lower Pulley Low-to-High Single-Arm Cable Fly", modality: 'tytax', sets: 3, reps: '12-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-single-arm-kneeling-lat-pulldown', exerciseName: "Upper Pulley Single-Arm Kneeling Lat Pulldown", modality: 'tytax', sets: 3, reps: '10-15/side', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-rope-row-elbows-high-for-rear-delts', exerciseName: "Lower Pulley Rope Row (elbows high for rear delts)", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-single-arm-lateral-raise', exerciseName: "Lower Pulley Single-Arm Lateral Raise", modality: 'tytax', sets: 3, reps: '15-20/side', restSeconds: 45 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-preacher-curl-bench-support', exerciseName: "Lower Pulley Preacher Curl (bench support)", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-rope-triceps-pushdown', exerciseName: "Upper Pulley Rope Triceps Pushdown", modality: 'tytax', sets: 3, reps: '12-15', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-lower-c',
      programId: '', // presets get an id when installed
      name: 'Lower C',
      dayIndex: 5,
      exercises: [
        { exerciseId: 'tytax_smith-machine_smith-bulgarian-split-squat', exerciseName: "Smith Bulgarian Split Squat", modality: 'tytax', sets: 3, reps: '10-12/leg', restSeconds: 90 },
        { exerciseId: 'tytax_back-lower-pulley_lower-pulley-kneeling-hamstring-curl-ankle-strap', exerciseName: "Lower Pulley Kneeling Hamstring Curl (ankle strap)", modality: 'tytax', sets: 3, reps: '10-15/leg', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-single-leg-hip-thrust', exerciseName: "Smith Single-Leg Hip Thrust", modality: 'tytax', sets: 2, reps: '10-15/leg', restSeconds: 60 },
        { exerciseId: 'tytax_smith-machine_smith-single-leg-standing-calf-raise', exerciseName: "Smith Single-Leg Standing Calf Raise", modality: 'tytax', sets: 2, reps: '12-20/leg', restSeconds: 60 },
        { exerciseId: 'tytax_back-upper-pulley_upper-pulley-high-to-low-woodchop', exerciseName: "Upper Pulley High-to-Low Woodchop", modality: 'tytax', sets: 2, reps: '10-15/side', restSeconds: 60 },
      ],
    },
    {
      id: 'preset-tytax-rest',
      programId: '',
      name: 'Rest',
      dayIndex: 6,
      exercises: [],
      isRest: true,
    },
  ],
};
