// G3's local tables, Wave 2 machine setup + time-measured sets.
// Generated by G4 (scratchpad merge_i18n_w2.py); edit the source table, then re-merge.
import type { g3SessionEn } from './g3Session.en';

export const g3SessionHr: Record<keyof typeof g3SessionEn, string> = {
  // src/components/workout/strings/setup.ts (SETUP_STRINGS)
  setup_label: 'Postavke sprave',
  setup_edit: 'Uredi postavke sprave',
  setup_sheet_title: 'Postavke: {name}',
  setup_seat: 'Sjedalo',
  setup_pin: 'Klin',
  setup_backrest: 'Naslon',
  setup_benchAngle: 'Kut klupe',
  setup_cable: 'Sajla',
  setup_other: 'Ostalo',
  setup_hint: 'Ostavi polje prazno da ga obrišeš.',
  setup_save: 'Spremi postavke',
  setup_saving: 'Spremanje…',
  setup_readonly: 'Spremanje postavki još nije dostupno na ovom uređaju, pa su prikazane samo za čitanje.',
  setup_error: 'Spremanje postavki nije uspjelo. Pokušaj ponovno.',
  order_station: 'Poredaj po stanici',
  order_station_done: 'Vježbe su preslagane da bude što manje promjena stanice.',
  order_station_same: 'Već su poredane po stanici.',
  order_station_error: 'Preslagivanje vježbi nije uspjelo.',
  // src/components/workout/strings/time.ts (TIME_STRINGS)
  time_duration: 'Trajanje (sekunde ili m:ss)',
  time_placeholder: 'sek',
  time_ghost: 'Prošli put {time}',
  time_hold_start: 'Pokreni mjerenje izdržaja',
  time_hold_stop: 'Zaustavi mjerenje na {time} i spremi',
  time_rir: 'RIR, ponavljanja u rezervi (0-5), neobavezno',
  time_done_needs_duration: 'Prvo unesi trajanje ili izmjeri izdržaj',
};
