// G3's local tables, Wave 2 machine setup + time-measured sets.
// Generated by G4 (scratchpad merge_i18n_w2.py); edit the source table, then re-merge.
export const g3SessionEn = {
  // src/components/workout/strings/setup.ts (SETUP_STRINGS)
  setup_label: 'Machine setup',
  setup_edit: 'Edit machine setup',
  setup_sheet_title: 'Setup: {name}',
  setup_seat: 'Seat',
  setup_pin: 'Pin',
  setup_backrest: 'Backrest',
  setup_benchAngle: 'Bench angle',
  setup_cable: 'Cable',
  setup_other: 'Other',
  setup_hint: 'Leave a field empty to clear it.',
  setup_save: 'Save setup',
  setup_saving: 'Saving…',
  setup_readonly: 'Saving a setup is not available on this device yet, so it is shown read-only.',
  setup_error: 'Could not save the setup. Try again.',
  order_station: 'Order by station',
  order_station_done: 'Exercises reordered to minimise station changes.',
  order_station_same: 'Already in station order.',
  order_station_error: 'Could not reorder the exercises.',
  // src/components/workout/strings/time.ts (TIME_STRINGS)
  time_duration: 'Duration (seconds or m:ss)',
  time_placeholder: 'sec',
  time_ghost: 'Last time {time}',
  time_hold_start: 'Start hold timer',
  time_hold_stop: 'Stop hold timer at {time} and save it',
  time_rir: 'RIR, reps in reserve (0-5), optional',
  time_done_needs_duration: 'Enter a duration or time the hold first',
} as const;
