// Generated by hand to match youth.en.ts key-for-key (hr is the default locale).
import type { youthEn } from './youth.en';

export const youthHr: Record<keyof typeof youthEn, string> = {
  youth_birth_year_label: 'Godina rođenja',
  youth_birth_year_hint: 'Neobavezno. Ispod 16 godina uključuje način za mlade: blaže automatsko povećanje utega i dodatne sigurnosne granice.',
  youth_birth_year_error: 'Unesi godinu između {min} i {max}.',
  youth_mode_badge: 'Način za mlade',
  youth_mode_hint: 'Blaže automatsko povećanje utega, bez drop/failure serija, bez preskakanja dana odmora, bez upozorenja o naglom skoku opterećenja.',
  youth_set_type_drop: 'Drop serija',
  youth_set_type_failure: 'Serija do otkaza',
  youth_preset_safety: 'Uz nadzor odrasle osobe. Prvo zagrijavanje 5 minuta. Odmah prekini ako zaboli. Tehnika je važnija od broja ponavljanja.',
};
